// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aiseats.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getActiveAISeatCount = `-- name: GetActiveAISeatCount :one
SELECT
	COUNT(*)
FROM
	ai_seat_state ais
JOIN
	users u
ON
	ais.user_id = u.id
WHERE
	u.status = 'active'::user_status
	AND u.deleted = false
	AND u.is_system = false
`

func (q *Queries) GetActiveAISeatCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveAISeatCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertAISeatState = `-- name: UpsertAISeatState :one
INSERT INTO ai_seat_state (
	user_id,
	first_used_at,
	last_used_at,
	last_event_type,
	last_event_description,
	updated_at
)
VALUES
	($1, $2, $2, $3, $4, $2)
ON CONFLICT (user_id) DO UPDATE
SET
	last_used_at = EXCLUDED.last_used_at,
	last_event_type = EXCLUDED.last_event_type,
	last_event_description = EXCLUDED.last_event_description,
	updated_at = EXCLUDED.updated_at
RETURNING
	-- Postgres vodoo to know if a row was inserted.
	(xmax = 0)::boolean AS is_new
`

type UpsertAISeatStateParams struct {
	UserID               uuid.UUID         `db:"user_id" json:"user_id"`
	FirstUsedAt          time.Time         `db:"first_used_at" json:"first_used_at"`
	LastEventType        AiSeatUsageReason `db:"last_event_type" json:"last_event_type"`
	LastEventDescription string            `db:"last_event_description" json:"last_event_description"`
}

// Returns true if a new rows was inserted, false otherwise.
func (q *Queries) UpsertAISeatState(ctx context.Context, arg UpsertAISeatStateParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, upsertAISeatState,
		arg.UserID,
		arg.FirstUsedAt,
		arg.LastEventType,
		arg.LastEventDescription,
	)
	var is_new bool
	err := row.Scan(&is_new)
	return is_new, err
}
