// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boundaryusagestats.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAndResetBoundaryUsageSummary = `-- name: GetAndResetBoundaryUsageSummary :one
WITH deleted AS (
    DELETE FROM boundary_usage_stats
    RETURNING replica_id, unique_workspaces_count, unique_users_count, allowed_requests, denied_requests, window_start, updated_at
)
SELECT
    COALESCE(SUM(unique_workspaces_count) FILTER (
        WHERE window_start >= NOW() - ($1::bigint || ' ms')::interval
    ), 0)::bigint AS unique_workspaces,
    COALESCE(SUM(unique_users_count) FILTER (
        WHERE window_start >= NOW() - ($1::bigint || ' ms')::interval
    ), 0)::bigint AS unique_users,
    COALESCE(SUM(allowed_requests) FILTER (
        WHERE window_start >= NOW() - ($1::bigint || ' ms')::interval
    ), 0)::bigint AS allowed_requests,
    COALESCE(SUM(denied_requests) FILTER (
        WHERE window_start >= NOW() - ($1::bigint || ' ms')::interval
    ), 0)::bigint AS denied_requests
FROM deleted
`

type GetAndResetBoundaryUsageSummaryRow struct {
	UniqueWorkspaces int64 `db:"unique_workspaces" json:"unique_workspaces"`
	UniqueUsers      int64 `db:"unique_users" json:"unique_users"`
	AllowedRequests  int64 `db:"allowed_requests" json:"allowed_requests"`
	DeniedRequests   int64 `db:"denied_requests" json:"denied_requests"`
}

// Atomic read+delete prevents replicas that flush between a separate read and
// reset from having their data deleted before the next snapshot. Uses a common
// table expression with DELETE...RETURNING so the rows we sum are exactly the
// rows we delete. Stale rows are excluded from the sum but still deleted.
func (q *Queries) GetAndResetBoundaryUsageSummary(ctx context.Context, maxStalenessMs int64) (GetAndResetBoundaryUsageSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getAndResetBoundaryUsageSummary, maxStalenessMs)
	var i GetAndResetBoundaryUsageSummaryRow
	err := row.Scan(
		&i.UniqueWorkspaces,
		&i.UniqueUsers,
		&i.AllowedRequests,
		&i.DeniedRequests,
	)
	return i, err
}

const upsertBoundaryUsageStats = `-- name: UpsertBoundaryUsageStats :one
INSERT INTO boundary_usage_stats (
    replica_id,
    unique_workspaces_count,
    unique_users_count,
    allowed_requests,
    denied_requests,
    window_start,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
) ON CONFLICT (replica_id) DO UPDATE SET
    unique_workspaces_count = $6,
    unique_users_count = $7,
    allowed_requests = boundary_usage_stats.allowed_requests + EXCLUDED.allowed_requests,
    denied_requests = boundary_usage_stats.denied_requests + EXCLUDED.denied_requests,
    updated_at = NOW()
RETURNING (xmax = 0) AS new_period
`

type UpsertBoundaryUsageStatsParams struct {
	ReplicaID             uuid.UUID `db:"replica_id" json:"replica_id"`
	UniqueWorkspacesDelta int64     `db:"unique_workspaces_delta" json:"unique_workspaces_delta"`
	UniqueUsersDelta      int64     `db:"unique_users_delta" json:"unique_users_delta"`
	AllowedRequests       int64     `db:"allowed_requests" json:"allowed_requests"`
	DeniedRequests        int64     `db:"denied_requests" json:"denied_requests"`
	UniqueWorkspacesCount int64     `db:"unique_workspaces_count" json:"unique_workspaces_count"`
	UniqueUsersCount      int64     `db:"unique_users_count" json:"unique_users_count"`
}

// Upserts boundary usage statistics for a replica. On INSERT (new period), uses
// delta values for unique counts (only data since last flush). On UPDATE, uses
// cumulative values for unique counts (accurate period totals). Request counts
// are always deltas, accumulated in DB. Returns true if insert, false if update.
func (q *Queries) UpsertBoundaryUsageStats(ctx context.Context, arg UpsertBoundaryUsageStatsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, upsertBoundaryUsageStats,
		arg.ReplicaID,
		arg.UniqueWorkspacesDelta,
		arg.UniqueUsersDelta,
		arg.AllowedRequests,
		arg.DeniedRequests,
		arg.UniqueWorkspacesCount,
		arg.UniqueUsersCount,
	)
	var new_period bool
	err := row.Scan(&new_period)
	return new_period, err
}
