// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chatmodelconfigs.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const deleteChatModelConfigByID = `-- name: DeleteChatModelConfigByID :exec
UPDATE
    chat_model_configs
SET
    deleted = TRUE,
    deleted_at = NOW(),
    updated_at = NOW()
WHERE
    id = $1::uuid
`

func (q *Queries) DeleteChatModelConfigByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChatModelConfigByID, id)
	return err
}

const getChatModelConfigByID = `-- name: GetChatModelConfigByID :one
SELECT
    id, provider, model, display_name, created_by, updated_by, enabled, is_default, deleted, deleted_at, created_at, updated_at, context_limit, compression_threshold, options
FROM
    chat_model_configs
WHERE
    id = $1::uuid
    AND deleted = FALSE
`

func (q *Queries) GetChatModelConfigByID(ctx context.Context, id uuid.UUID) (ChatModelConfig, error) {
	row := q.db.QueryRowContext(ctx, getChatModelConfigByID, id)
	var i ChatModelConfig
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.DisplayName,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Enabled,
		&i.IsDefault,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContextLimit,
		&i.CompressionThreshold,
		&i.Options,
	)
	return i, err
}

const getChatModelConfigs = `-- name: GetChatModelConfigs :many
SELECT
    id, provider, model, display_name, created_by, updated_by, enabled, is_default, deleted, deleted_at, created_at, updated_at, context_limit, compression_threshold, options
FROM
    chat_model_configs
WHERE
    deleted = FALSE
ORDER BY
    provider ASC,
    model ASC,
    updated_at DESC,
    id DESC
`

func (q *Queries) GetChatModelConfigs(ctx context.Context) ([]ChatModelConfig, error) {
	rows, err := q.db.QueryContext(ctx, getChatModelConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatModelConfig
	for rows.Next() {
		var i ChatModelConfig
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.DisplayName,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Enabled,
			&i.IsDefault,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContextLimit,
			&i.CompressionThreshold,
			&i.Options,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDefaultChatModelConfig = `-- name: GetDefaultChatModelConfig :one
SELECT
    id, provider, model, display_name, created_by, updated_by, enabled, is_default, deleted, deleted_at, created_at, updated_at, context_limit, compression_threshold, options
FROM
    chat_model_configs
WHERE
    is_default = TRUE
    AND deleted = FALSE
`

func (q *Queries) GetDefaultChatModelConfig(ctx context.Context) (ChatModelConfig, error) {
	row := q.db.QueryRowContext(ctx, getDefaultChatModelConfig)
	var i ChatModelConfig
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.DisplayName,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Enabled,
		&i.IsDefault,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContextLimit,
		&i.CompressionThreshold,
		&i.Options,
	)
	return i, err
}

const getEnabledChatModelConfigs = `-- name: GetEnabledChatModelConfigs :many
SELECT
    cmc.id, cmc.provider, cmc.model, cmc.display_name, cmc.created_by, cmc.updated_by, cmc.enabled, cmc.is_default, cmc.deleted, cmc.deleted_at, cmc.created_at, cmc.updated_at, cmc.context_limit, cmc.compression_threshold, cmc.options
FROM
    chat_model_configs cmc
JOIN
    chat_providers cp ON cp.provider = cmc.provider
WHERE
    cmc.enabled = TRUE
    AND cmc.deleted = FALSE
    AND cp.enabled = TRUE
ORDER BY
    cmc.provider ASC,
    cmc.model ASC,
    cmc.updated_at DESC,
    cmc.id DESC
`

func (q *Queries) GetEnabledChatModelConfigs(ctx context.Context) ([]ChatModelConfig, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledChatModelConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatModelConfig
	for rows.Next() {
		var i ChatModelConfig
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.DisplayName,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Enabled,
			&i.IsDefault,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContextLimit,
			&i.CompressionThreshold,
			&i.Options,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChatModelConfig = `-- name: InsertChatModelConfig :one
INSERT INTO chat_model_configs (
    provider,
    model,
    display_name,
    created_by,
    updated_by,
    enabled,
    is_default,
    context_limit,
    compression_threshold,
    options
) VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::uuid,
    $5::uuid,
    $6::boolean,
    $7::boolean,
    $8::bigint,
    $9::integer,
    $10::jsonb
)
RETURNING
    id, provider, model, display_name, created_by, updated_by, enabled, is_default, deleted, deleted_at, created_at, updated_at, context_limit, compression_threshold, options
`

type InsertChatModelConfigParams struct {
	Provider             string          `db:"provider" json:"provider"`
	Model                string          `db:"model" json:"model"`
	DisplayName          string          `db:"display_name" json:"display_name"`
	CreatedBy            uuid.NullUUID   `db:"created_by" json:"created_by"`
	UpdatedBy            uuid.NullUUID   `db:"updated_by" json:"updated_by"`
	Enabled              bool            `db:"enabled" json:"enabled"`
	IsDefault            bool            `db:"is_default" json:"is_default"`
	ContextLimit         int64           `db:"context_limit" json:"context_limit"`
	CompressionThreshold int32           `db:"compression_threshold" json:"compression_threshold"`
	Options              json.RawMessage `db:"options" json:"options"`
}

func (q *Queries) InsertChatModelConfig(ctx context.Context, arg InsertChatModelConfigParams) (ChatModelConfig, error) {
	row := q.db.QueryRowContext(ctx, insertChatModelConfig,
		arg.Provider,
		arg.Model,
		arg.DisplayName,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.Enabled,
		arg.IsDefault,
		arg.ContextLimit,
		arg.CompressionThreshold,
		arg.Options,
	)
	var i ChatModelConfig
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.DisplayName,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Enabled,
		&i.IsDefault,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContextLimit,
		&i.CompressionThreshold,
		&i.Options,
	)
	return i, err
}

const unsetDefaultChatModelConfigs = `-- name: UnsetDefaultChatModelConfigs :exec
UPDATE
    chat_model_configs
SET
    is_default = FALSE,
    updated_at = NOW()
WHERE
    is_default = TRUE
    AND deleted = FALSE
`

func (q *Queries) UnsetDefaultChatModelConfigs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, unsetDefaultChatModelConfigs)
	return err
}

const updateChatModelConfig = `-- name: UpdateChatModelConfig :one
UPDATE
    chat_model_configs
SET
    provider = $1::text,
    model = $2::text,
    display_name = $3::text,
    updated_by = $4::uuid,
    enabled = $5::boolean,
    is_default = $6::boolean,
    context_limit = $7::bigint,
    compression_threshold = $8::integer,
    options = $9::jsonb,
    updated_at = NOW()
WHERE
    id = $10::uuid
    AND deleted = FALSE
RETURNING
    id, provider, model, display_name, created_by, updated_by, enabled, is_default, deleted, deleted_at, created_at, updated_at, context_limit, compression_threshold, options
`

type UpdateChatModelConfigParams struct {
	Provider             string          `db:"provider" json:"provider"`
	Model                string          `db:"model" json:"model"`
	DisplayName          string          `db:"display_name" json:"display_name"`
	UpdatedBy            uuid.NullUUID   `db:"updated_by" json:"updated_by"`
	Enabled              bool            `db:"enabled" json:"enabled"`
	IsDefault            bool            `db:"is_default" json:"is_default"`
	ContextLimit         int64           `db:"context_limit" json:"context_limit"`
	CompressionThreshold int32           `db:"compression_threshold" json:"compression_threshold"`
	Options              json.RawMessage `db:"options" json:"options"`
	ID                   uuid.UUID       `db:"id" json:"id"`
}

func (q *Queries) UpdateChatModelConfig(ctx context.Context, arg UpdateChatModelConfigParams) (ChatModelConfig, error) {
	row := q.db.QueryRowContext(ctx, updateChatModelConfig,
		arg.Provider,
		arg.Model,
		arg.DisplayName,
		arg.UpdatedBy,
		arg.Enabled,
		arg.IsDefault,
		arg.ContextLimit,
		arg.CompressionThreshold,
		arg.Options,
		arg.ID,
	)
	var i ChatModelConfig
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.DisplayName,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Enabled,
		&i.IsDefault,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContextLimit,
		&i.CompressionThreshold,
		&i.Options,
	)
	return i, err
}
