// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chatproviders.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteChatProviderByID = `-- name: DeleteChatProviderByID :exec
DELETE FROM
    chat_providers
WHERE
    id = $1::uuid
`

func (q *Queries) DeleteChatProviderByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChatProviderByID, id)
	return err
}

const getChatProviderByID = `-- name: GetChatProviderByID :one
SELECT
    id, provider, display_name, api_key, api_key_key_id, created_by, enabled, created_at, updated_at, base_url
FROM
    chat_providers
WHERE
    id = $1::uuid
`

func (q *Queries) GetChatProviderByID(ctx context.Context, id uuid.UUID) (ChatProvider, error) {
	row := q.db.QueryRowContext(ctx, getChatProviderByID, id)
	var i ChatProvider
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.DisplayName,
		&i.APIKey,
		&i.ApiKeyKeyID,
		&i.CreatedBy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaseUrl,
	)
	return i, err
}

const getChatProviderByProvider = `-- name: GetChatProviderByProvider :one
SELECT
    id, provider, display_name, api_key, api_key_key_id, created_by, enabled, created_at, updated_at, base_url
FROM
    chat_providers
WHERE
    provider = $1::text
`

func (q *Queries) GetChatProviderByProvider(ctx context.Context, provider string) (ChatProvider, error) {
	row := q.db.QueryRowContext(ctx, getChatProviderByProvider, provider)
	var i ChatProvider
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.DisplayName,
		&i.APIKey,
		&i.ApiKeyKeyID,
		&i.CreatedBy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaseUrl,
	)
	return i, err
}

const getChatProviders = `-- name: GetChatProviders :many
SELECT
    id, provider, display_name, api_key, api_key_key_id, created_by, enabled, created_at, updated_at, base_url
FROM
    chat_providers
ORDER BY
    provider ASC
`

func (q *Queries) GetChatProviders(ctx context.Context) ([]ChatProvider, error) {
	rows, err := q.db.QueryContext(ctx, getChatProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatProvider
	for rows.Next() {
		var i ChatProvider
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.DisplayName,
			&i.APIKey,
			&i.ApiKeyKeyID,
			&i.CreatedBy,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnabledChatProviders = `-- name: GetEnabledChatProviders :many
SELECT
    id, provider, display_name, api_key, api_key_key_id, created_by, enabled, created_at, updated_at, base_url
FROM
    chat_providers
WHERE
    enabled = TRUE
ORDER BY
    provider ASC
`

func (q *Queries) GetEnabledChatProviders(ctx context.Context) ([]ChatProvider, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledChatProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatProvider
	for rows.Next() {
		var i ChatProvider
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.DisplayName,
			&i.APIKey,
			&i.ApiKeyKeyID,
			&i.CreatedBy,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChatProvider = `-- name: InsertChatProvider :one
INSERT INTO chat_providers (
    provider,
    display_name,
    api_key,
    base_url,
    api_key_key_id,
    created_by,
    enabled
) VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    $6::uuid,
    $7::boolean
)
RETURNING
    id, provider, display_name, api_key, api_key_key_id, created_by, enabled, created_at, updated_at, base_url
`

type InsertChatProviderParams struct {
	Provider    string         `db:"provider" json:"provider"`
	DisplayName string         `db:"display_name" json:"display_name"`
	APIKey      string         `db:"api_key" json:"api_key"`
	BaseUrl     string         `db:"base_url" json:"base_url"`
	ApiKeyKeyID sql.NullString `db:"api_key_key_id" json:"api_key_key_id"`
	CreatedBy   uuid.NullUUID  `db:"created_by" json:"created_by"`
	Enabled     bool           `db:"enabled" json:"enabled"`
}

func (q *Queries) InsertChatProvider(ctx context.Context, arg InsertChatProviderParams) (ChatProvider, error) {
	row := q.db.QueryRowContext(ctx, insertChatProvider,
		arg.Provider,
		arg.DisplayName,
		arg.APIKey,
		arg.BaseUrl,
		arg.ApiKeyKeyID,
		arg.CreatedBy,
		arg.Enabled,
	)
	var i ChatProvider
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.DisplayName,
		&i.APIKey,
		&i.ApiKeyKeyID,
		&i.CreatedBy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaseUrl,
	)
	return i, err
}

const updateChatProvider = `-- name: UpdateChatProvider :one
UPDATE
    chat_providers
SET
    display_name = $1::text,
    api_key = $2::text,
    base_url = $3::text,
    api_key_key_id = $4::text,
    enabled = $5::boolean,
    updated_at = NOW()
WHERE
    id = $6::uuid
RETURNING
    id, provider, display_name, api_key, api_key_key_id, created_by, enabled, created_at, updated_at, base_url
`

type UpdateChatProviderParams struct {
	DisplayName string         `db:"display_name" json:"display_name"`
	APIKey      string         `db:"api_key" json:"api_key"`
	BaseUrl     string         `db:"base_url" json:"base_url"`
	ApiKeyKeyID sql.NullString `db:"api_key_key_id" json:"api_key_key_id"`
	Enabled     bool           `db:"enabled" json:"enabled"`
	ID          uuid.UUID      `db:"id" json:"id"`
}

func (q *Queries) UpdateChatProvider(ctx context.Context, arg UpdateChatProviderParams) (ChatProvider, error) {
	row := q.db.QueryRowContext(ctx, updateChatProvider,
		arg.DisplayName,
		arg.APIKey,
		arg.BaseUrl,
		arg.ApiKeyKeyID,
		arg.Enabled,
		arg.ID,
	)
	var i ChatProvider
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.DisplayName,
		&i.APIKey,
		&i.ApiKeyKeyID,
		&i.CreatedBy,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaseUrl,
	)
	return i, err
}
