// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const acquireChats = `-- name: AcquireChats :many
UPDATE
    chats
SET
    status = 'running'::chat_status,
    started_at = $1::timestamptz,
    heartbeat_at = $1::timestamptz,
    updated_at = $1::timestamptz,
    worker_id = $2::uuid
WHERE
    id = ANY(
        SELECT
            id
        FROM
            chats
        WHERE
            status = 'pending'::chat_status
        ORDER BY
            updated_at ASC
        FOR UPDATE
            SKIP LOCKED
        LIMIT
            $3::int
    )
RETURNING
    id, owner_id, workspace_id, title, status, worker_id, started_at, heartbeat_at, created_at, updated_at, parent_chat_id, root_chat_id, last_model_config_id, archived, last_error, mode, mcp_server_ids
`

type AcquireChatsParams struct {
	StartedAt time.Time `db:"started_at" json:"started_at"`
	WorkerID  uuid.UUID `db:"worker_id" json:"worker_id"`
	NumChats  int32     `db:"num_chats" json:"num_chats"`
}

// Acquires up to @num_chats pending chats for processing. Uses SKIP LOCKED
// to prevent multiple replicas from acquiring the same chat.
func (q *Queries) AcquireChats(ctx context.Context, arg AcquireChatsParams) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, acquireChats, arg.StartedAt, arg.WorkerID, arg.NumChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.WorkspaceID,
			&i.Title,
			&i.Status,
			&i.WorkerID,
			&i.StartedAt,
			&i.HeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentChatID,
			&i.RootChatID,
			&i.LastModelConfigID,
			&i.Archived,
			&i.LastError,
			&i.Mode,
			pq.Array(&i.MCPServerIDs),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const acquireStaleChatDiffStatuses = `-- name: AcquireStaleChatDiffStatuses :many
WITH acquired AS (
    UPDATE
        chat_diff_statuses
    SET
        -- Claim for 5 minutes. The worker sets the real stale_at
        -- after refresh. If the worker crashes, rows become eligible
        -- again after this interval.
        stale_at = NOW() + INTERVAL '5 minutes',
        updated_at = NOW()
    WHERE
        chat_id IN (
            SELECT
                cds.chat_id
            FROM
                chat_diff_statuses cds
            INNER JOIN
                chats c ON c.id = cds.chat_id
            WHERE
                cds.stale_at <= NOW()
                AND cds.git_remote_origin != ''
                AND cds.git_branch != ''
                AND c.archived = FALSE
            ORDER BY
                cds.stale_at ASC
            FOR UPDATE OF cds
                SKIP LOCKED
            LIMIT
                $1::int
        )
    RETURNING chat_id, url, pull_request_state, changes_requested, additions, deletions, changed_files, refreshed_at, stale_at, created_at, updated_at, git_branch, git_remote_origin, pull_request_title, pull_request_draft, author_login, author_avatar_url, base_branch, pr_number, commits, approved, reviewer_count, head_branch
)
SELECT
    acquired.chat_id, acquired.url, acquired.pull_request_state, acquired.changes_requested, acquired.additions, acquired.deletions, acquired.changed_files, acquired.refreshed_at, acquired.stale_at, acquired.created_at, acquired.updated_at, acquired.git_branch, acquired.git_remote_origin, acquired.pull_request_title, acquired.pull_request_draft, acquired.author_login, acquired.author_avatar_url, acquired.base_branch, acquired.pr_number, acquired.commits, acquired.approved, acquired.reviewer_count, acquired.head_branch,
    c.owner_id
FROM
    acquired
INNER JOIN
    chats c ON c.id = acquired.chat_id
`

type AcquireStaleChatDiffStatusesRow struct {
	ChatID           uuid.UUID      `db:"chat_id" json:"chat_id"`
	Url              sql.NullString `db:"url" json:"url"`
	PullRequestState sql.NullString `db:"pull_request_state" json:"pull_request_state"`
	ChangesRequested bool           `db:"changes_requested" json:"changes_requested"`
	Additions        int32          `db:"additions" json:"additions"`
	Deletions        int32          `db:"deletions" json:"deletions"`
	ChangedFiles     int32          `db:"changed_files" json:"changed_files"`
	RefreshedAt      sql.NullTime   `db:"refreshed_at" json:"refreshed_at"`
	StaleAt          time.Time      `db:"stale_at" json:"stale_at"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time      `db:"updated_at" json:"updated_at"`
	GitBranch        string         `db:"git_branch" json:"git_branch"`
	GitRemoteOrigin  string         `db:"git_remote_origin" json:"git_remote_origin"`
	PullRequestTitle string         `db:"pull_request_title" json:"pull_request_title"`
	PullRequestDraft bool           `db:"pull_request_draft" json:"pull_request_draft"`
	AuthorLogin      sql.NullString `db:"author_login" json:"author_login"`
	AuthorAvatarUrl  sql.NullString `db:"author_avatar_url" json:"author_avatar_url"`
	BaseBranch       sql.NullString `db:"base_branch" json:"base_branch"`
	PrNumber         sql.NullInt32  `db:"pr_number" json:"pr_number"`
	Commits          sql.NullInt32  `db:"commits" json:"commits"`
	Approved         sql.NullBool   `db:"approved" json:"approved"`
	ReviewerCount    sql.NullInt32  `db:"reviewer_count" json:"reviewer_count"`
	HeadBranch       sql.NullString `db:"head_branch" json:"head_branch"`
	OwnerID          uuid.UUID      `db:"owner_id" json:"owner_id"`
}

func (q *Queries) AcquireStaleChatDiffStatuses(ctx context.Context, limitVal int32) ([]AcquireStaleChatDiffStatusesRow, error) {
	rows, err := q.db.QueryContext(ctx, acquireStaleChatDiffStatuses, limitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcquireStaleChatDiffStatusesRow
	for rows.Next() {
		var i AcquireStaleChatDiffStatusesRow
		if err := rows.Scan(
			&i.ChatID,
			&i.Url,
			&i.PullRequestState,
			&i.ChangesRequested,
			&i.Additions,
			&i.Deletions,
			&i.ChangedFiles,
			&i.RefreshedAt,
			&i.StaleAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GitBranch,
			&i.GitRemoteOrigin,
			&i.PullRequestTitle,
			&i.PullRequestDraft,
			&i.AuthorLogin,
			&i.AuthorAvatarUrl,
			&i.BaseBranch,
			&i.PrNumber,
			&i.Commits,
			&i.Approved,
			&i.ReviewerCount,
			&i.HeadBranch,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const archiveChatByID = `-- name: ArchiveChatByID :exec
UPDATE chats SET archived = true, updated_at = NOW()
WHERE id = $1 OR root_chat_id = $1
`

func (q *Queries) ArchiveChatByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, archiveChatByID, id)
	return err
}

const backoffChatDiffStatus = `-- name: BackoffChatDiffStatus :exec
UPDATE
    chat_diff_statuses
SET
    stale_at = $1::timestamptz,
    updated_at = NOW()
WHERE
    chat_id = $2::uuid
`

type BackoffChatDiffStatusParams struct {
	StaleAt time.Time `db:"stale_at" json:"stale_at"`
	ChatID  uuid.UUID `db:"chat_id" json:"chat_id"`
}

func (q *Queries) BackoffChatDiffStatus(ctx context.Context, arg BackoffChatDiffStatusParams) error {
	_, err := q.db.ExecContext(ctx, backoffChatDiffStatus, arg.StaleAt, arg.ChatID)
	return err
}

const countEnabledModelsWithoutPricing = `-- name: CountEnabledModelsWithoutPricing :one
SELECT COUNT(*)::bigint AS count
FROM chat_model_configs
WHERE enabled = TRUE
  AND deleted = FALSE
  AND (
    options->'cost' IS NULL
    OR options->'cost' = 'null'::jsonb
    OR (
      (options->'cost'->>'input_price_per_million_tokens' IS NULL)
      AND (options->'cost'->>'output_price_per_million_tokens' IS NULL)
    )
  )
`

// Counts enabled, non-deleted model configs that lack both input and
// output pricing in their JSONB options.cost configuration.
func (q *Queries) CountEnabledModelsWithoutPricing(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledModelsWithoutPricing)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllChatQueuedMessages = `-- name: DeleteAllChatQueuedMessages :exec
DELETE FROM chat_queued_messages WHERE chat_id = $1
`

func (q *Queries) DeleteAllChatQueuedMessages(ctx context.Context, chatID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllChatQueuedMessages, chatID)
	return err
}

const deleteChatQueuedMessage = `-- name: DeleteChatQueuedMessage :exec
DELETE FROM chat_queued_messages WHERE id = $1 AND chat_id = $2
`

type DeleteChatQueuedMessageParams struct {
	ID     int64     `db:"id" json:"id"`
	ChatID uuid.UUID `db:"chat_id" json:"chat_id"`
}

func (q *Queries) DeleteChatQueuedMessage(ctx context.Context, arg DeleteChatQueuedMessageParams) error {
	_, err := q.db.ExecContext(ctx, deleteChatQueuedMessage, arg.ID, arg.ChatID)
	return err
}

const deleteChatUsageLimitGroupOverride = `-- name: DeleteChatUsageLimitGroupOverride :exec
UPDATE groups SET chat_spend_limit_micros = NULL WHERE id = $1::uuid
`

func (q *Queries) DeleteChatUsageLimitGroupOverride(ctx context.Context, groupID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChatUsageLimitGroupOverride, groupID)
	return err
}

const deleteChatUsageLimitUserOverride = `-- name: DeleteChatUsageLimitUserOverride :exec
UPDATE users SET chat_spend_limit_micros = NULL WHERE id = $1::uuid
`

func (q *Queries) DeleteChatUsageLimitUserOverride(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChatUsageLimitUserOverride, userID)
	return err
}

const getChatByID = `-- name: GetChatByID :one
SELECT
    id, owner_id, workspace_id, title, status, worker_id, started_at, heartbeat_at, created_at, updated_at, parent_chat_id, root_chat_id, last_model_config_id, archived, last_error, mode, mcp_server_ids
FROM
    chats
WHERE
    id = $1::uuid
`

func (q *Queries) GetChatByID(ctx context.Context, id uuid.UUID) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.WorkspaceID,
		&i.Title,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentChatID,
		&i.RootChatID,
		&i.LastModelConfigID,
		&i.Archived,
		&i.LastError,
		&i.Mode,
		pq.Array(&i.MCPServerIDs),
	)
	return i, err
}

const getChatByIDForUpdate = `-- name: GetChatByIDForUpdate :one
SELECT id, owner_id, workspace_id, title, status, worker_id, started_at, heartbeat_at, created_at, updated_at, parent_chat_id, root_chat_id, last_model_config_id, archived, last_error, mode, mcp_server_ids FROM chats WHERE id = $1::uuid FOR UPDATE
`

func (q *Queries) GetChatByIDForUpdate(ctx context.Context, id uuid.UUID) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByIDForUpdate, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.WorkspaceID,
		&i.Title,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentChatID,
		&i.RootChatID,
		&i.LastModelConfigID,
		&i.Archived,
		&i.LastError,
		&i.Mode,
		pq.Array(&i.MCPServerIDs),
	)
	return i, err
}

const getChatCostPerChat = `-- name: GetChatCostPerChat :many
WITH chat_costs AS (
    SELECT
        COALESCE(c.root_chat_id, c.id) AS root_chat_id,
        COALESCE(SUM(cm.total_cost_micros), 0)::bigint AS total_cost_micros,
        COUNT(*) FILTER (
            WHERE cm.input_tokens IS NOT NULL
                OR cm.output_tokens IS NOT NULL
                OR cm.reasoning_tokens IS NOT NULL
                OR cm.cache_creation_tokens IS NOT NULL
                OR cm.cache_read_tokens IS NOT NULL
        )::bigint AS message_count,
        COALESCE(SUM(cm.input_tokens), 0)::bigint AS total_input_tokens,
        COALESCE(SUM(cm.output_tokens), 0)::bigint AS total_output_tokens,
        COALESCE(SUM(cm.cache_read_tokens), 0)::bigint AS total_cache_read_tokens,
        COALESCE(SUM(cm.cache_creation_tokens), 0)::bigint AS total_cache_creation_tokens
    FROM chat_messages cm
    JOIN chats c ON c.id = cm.chat_id
    WHERE c.owner_id = $1::uuid
      AND cm.role = 'assistant'
      AND cm.created_at >= $2::timestamptz
      AND cm.created_at < $3::timestamptz
    GROUP BY COALESCE(c.root_chat_id, c.id)
)
SELECT
    cc.root_chat_id,
    COALESCE(rc.title, '') AS chat_title,
    cc.total_cost_micros,
    cc.message_count,
    cc.total_input_tokens,
    cc.total_output_tokens,
    cc.total_cache_read_tokens,
    cc.total_cache_creation_tokens
FROM chat_costs cc
LEFT JOIN chats rc ON rc.id = cc.root_chat_id
ORDER BY cc.total_cost_micros DESC
`

type GetChatCostPerChatParams struct {
	OwnerID   uuid.UUID `db:"owner_id" json:"owner_id"`
	StartDate time.Time `db:"start_date" json:"start_date"`
	EndDate   time.Time `db:"end_date" json:"end_date"`
}

type GetChatCostPerChatRow struct {
	RootChatID               uuid.UUID `db:"root_chat_id" json:"root_chat_id"`
	ChatTitle                string    `db:"chat_title" json:"chat_title"`
	TotalCostMicros          int64     `db:"total_cost_micros" json:"total_cost_micros"`
	MessageCount             int64     `db:"message_count" json:"message_count"`
	TotalInputTokens         int64     `db:"total_input_tokens" json:"total_input_tokens"`
	TotalOutputTokens        int64     `db:"total_output_tokens" json:"total_output_tokens"`
	TotalCacheReadTokens     int64     `db:"total_cache_read_tokens" json:"total_cache_read_tokens"`
	TotalCacheCreationTokens int64     `db:"total_cache_creation_tokens" json:"total_cache_creation_tokens"`
}

// Per-root-chat cost breakdown for a single user within a date range.
// Groups by root_chat_id so forked chats roll up under their root.
// Only counts assistant-role messages.
func (q *Queries) GetChatCostPerChat(ctx context.Context, arg GetChatCostPerChatParams) ([]GetChatCostPerChatRow, error) {
	rows, err := q.db.QueryContext(ctx, getChatCostPerChat, arg.OwnerID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatCostPerChatRow
	for rows.Next() {
		var i GetChatCostPerChatRow
		if err := rows.Scan(
			&i.RootChatID,
			&i.ChatTitle,
			&i.TotalCostMicros,
			&i.MessageCount,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.TotalCacheReadTokens,
			&i.TotalCacheCreationTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatCostPerModel = `-- name: GetChatCostPerModel :many
SELECT
    cmc.id AS model_config_id,
    cmc.display_name,
    cmc.provider,
    cmc.model,
    COALESCE(SUM(cm.total_cost_micros), 0)::bigint AS total_cost_micros,
    COUNT(*) FILTER (
        WHERE cm.input_tokens IS NOT NULL
            OR cm.output_tokens IS NOT NULL
            OR cm.reasoning_tokens IS NOT NULL
            OR cm.cache_creation_tokens IS NOT NULL
            OR cm.cache_read_tokens IS NOT NULL
    )::bigint AS message_count,
    COALESCE(SUM(cm.input_tokens), 0)::bigint AS total_input_tokens,
    COALESCE(SUM(cm.output_tokens), 0)::bigint AS total_output_tokens,
    COALESCE(SUM(cm.cache_read_tokens), 0)::bigint AS total_cache_read_tokens,
    COALESCE(SUM(cm.cache_creation_tokens), 0)::bigint AS total_cache_creation_tokens
FROM
    chat_messages cm
JOIN
    chats c ON c.id = cm.chat_id
JOIN
    chat_model_configs cmc ON cmc.id = cm.model_config_id
WHERE
    c.owner_id = $1::uuid
    AND cm.role = 'assistant'
    AND cm.created_at >= $2::timestamptz
    AND cm.created_at < $3::timestamptz
GROUP BY
    cmc.id, cmc.display_name, cmc.provider, cmc.model
ORDER BY
    total_cost_micros DESC
`

type GetChatCostPerModelParams struct {
	OwnerID   uuid.UUID `db:"owner_id" json:"owner_id"`
	StartDate time.Time `db:"start_date" json:"start_date"`
	EndDate   time.Time `db:"end_date" json:"end_date"`
}

type GetChatCostPerModelRow struct {
	ModelConfigID            uuid.UUID `db:"model_config_id" json:"model_config_id"`
	DisplayName              string    `db:"display_name" json:"display_name"`
	Provider                 string    `db:"provider" json:"provider"`
	Model                    string    `db:"model" json:"model"`
	TotalCostMicros          int64     `db:"total_cost_micros" json:"total_cost_micros"`
	MessageCount             int64     `db:"message_count" json:"message_count"`
	TotalInputTokens         int64     `db:"total_input_tokens" json:"total_input_tokens"`
	TotalOutputTokens        int64     `db:"total_output_tokens" json:"total_output_tokens"`
	TotalCacheReadTokens     int64     `db:"total_cache_read_tokens" json:"total_cache_read_tokens"`
	TotalCacheCreationTokens int64     `db:"total_cache_creation_tokens" json:"total_cache_creation_tokens"`
}

// Per-model cost breakdown for a single user within a date range.
// Only counts assistant-role messages that have a model_config_id.
func (q *Queries) GetChatCostPerModel(ctx context.Context, arg GetChatCostPerModelParams) ([]GetChatCostPerModelRow, error) {
	rows, err := q.db.QueryContext(ctx, getChatCostPerModel, arg.OwnerID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatCostPerModelRow
	for rows.Next() {
		var i GetChatCostPerModelRow
		if err := rows.Scan(
			&i.ModelConfigID,
			&i.DisplayName,
			&i.Provider,
			&i.Model,
			&i.TotalCostMicros,
			&i.MessageCount,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.TotalCacheReadTokens,
			&i.TotalCacheCreationTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatCostPerUser = `-- name: GetChatCostPerUser :many
WITH chat_cost_users AS (
    SELECT
        c.owner_id AS user_id,
        u.username,
        u.name,
        u.avatar_url,
        COALESCE(SUM(cm.total_cost_micros), 0)::bigint AS total_cost_micros,
        COUNT(*) FILTER (
            WHERE cm.input_tokens IS NOT NULL
                OR cm.output_tokens IS NOT NULL
                OR cm.reasoning_tokens IS NOT NULL
                OR cm.cache_creation_tokens IS NOT NULL
                OR cm.cache_read_tokens IS NOT NULL
        )::bigint AS message_count,
        COUNT(DISTINCT COALESCE(c.root_chat_id, c.id))::bigint AS chat_count,
        COALESCE(SUM(cm.input_tokens), 0)::bigint AS total_input_tokens,
        COALESCE(SUM(cm.output_tokens), 0)::bigint AS total_output_tokens,
        COALESCE(SUM(cm.cache_read_tokens), 0)::bigint AS total_cache_read_tokens,
        COALESCE(SUM(cm.cache_creation_tokens), 0)::bigint AS total_cache_creation_tokens
    FROM
        chat_messages cm
    JOIN
        chats c ON c.id = cm.chat_id
    JOIN
        users u ON u.id = c.owner_id
    WHERE
        cm.role = 'assistant'
        AND cm.created_at >= $3::timestamptz
        AND cm.created_at < $4::timestamptz
        AND (
            $5::text = ''
            OR u.username ILIKE '%' || $5::text || '%'
            OR u.name ILIKE '%' || $5::text || '%'
        )
    GROUP BY
        c.owner_id,
        u.username,
        u.name,
        u.avatar_url
)
SELECT
    user_id,
    username,
    name,
    avatar_url,
    total_cost_micros,
    message_count,
    chat_count,
    total_input_tokens,
    total_output_tokens,
    total_cache_read_tokens,
    total_cache_creation_tokens,
    COUNT(*) OVER()::bigint AS total_count
FROM
    chat_cost_users
ORDER BY
    total_cost_micros DESC,
    username ASC
LIMIT
    $2::int
OFFSET
    $1::int
`

type GetChatCostPerUserParams struct {
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageLimit  int32     `db:"page_limit" json:"page_limit"`
	StartDate  time.Time `db:"start_date" json:"start_date"`
	EndDate    time.Time `db:"end_date" json:"end_date"`
	Username   string    `db:"username" json:"username"`
}

type GetChatCostPerUserRow struct {
	UserID                   uuid.UUID `db:"user_id" json:"user_id"`
	Username                 string    `db:"username" json:"username"`
	Name                     string    `db:"name" json:"name"`
	AvatarURL                string    `db:"avatar_url" json:"avatar_url"`
	TotalCostMicros          int64     `db:"total_cost_micros" json:"total_cost_micros"`
	MessageCount             int64     `db:"message_count" json:"message_count"`
	ChatCount                int64     `db:"chat_count" json:"chat_count"`
	TotalInputTokens         int64     `db:"total_input_tokens" json:"total_input_tokens"`
	TotalOutputTokens        int64     `db:"total_output_tokens" json:"total_output_tokens"`
	TotalCacheReadTokens     int64     `db:"total_cache_read_tokens" json:"total_cache_read_tokens"`
	TotalCacheCreationTokens int64     `db:"total_cache_creation_tokens" json:"total_cache_creation_tokens"`
	TotalCount               int64     `db:"total_count" json:"total_count"`
}

// Deployment-wide per-user cost rollup within a date range.
// Only counts assistant-role messages.
func (q *Queries) GetChatCostPerUser(ctx context.Context, arg GetChatCostPerUserParams) ([]GetChatCostPerUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getChatCostPerUser,
		arg.PageOffset,
		arg.PageLimit,
		arg.StartDate,
		arg.EndDate,
		arg.Username,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatCostPerUserRow
	for rows.Next() {
		var i GetChatCostPerUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Name,
			&i.AvatarURL,
			&i.TotalCostMicros,
			&i.MessageCount,
			&i.ChatCount,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.TotalCacheReadTokens,
			&i.TotalCacheCreationTokens,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatCostSummary = `-- name: GetChatCostSummary :one
SELECT
    COALESCE(SUM(cm.total_cost_micros), 0)::bigint AS total_cost_micros,
    COUNT(*) FILTER (
        WHERE cm.total_cost_micros IS NOT NULL
    )::bigint AS priced_message_count,
    COUNT(*) FILTER (
        WHERE cm.total_cost_micros IS NULL
            AND (
                cm.input_tokens IS NOT NULL
                OR cm.output_tokens IS NOT NULL
                OR cm.reasoning_tokens IS NOT NULL
                OR cm.cache_creation_tokens IS NOT NULL
                OR cm.cache_read_tokens IS NOT NULL
            )
    )::bigint AS unpriced_message_count,
    COALESCE(SUM(cm.input_tokens), 0)::bigint AS total_input_tokens,
    COALESCE(SUM(cm.output_tokens), 0)::bigint AS total_output_tokens,
    COALESCE(SUM(cm.cache_read_tokens), 0)::bigint AS total_cache_read_tokens,
    COALESCE(SUM(cm.cache_creation_tokens), 0)::bigint AS total_cache_creation_tokens
FROM
    chat_messages cm
JOIN
    chats c ON c.id = cm.chat_id
WHERE
    c.owner_id = $1::uuid
    AND cm.role = 'assistant'
    AND cm.created_at >= $2::timestamptz
    AND cm.created_at < $3::timestamptz
`

type GetChatCostSummaryParams struct {
	OwnerID   uuid.UUID `db:"owner_id" json:"owner_id"`
	StartDate time.Time `db:"start_date" json:"start_date"`
	EndDate   time.Time `db:"end_date" json:"end_date"`
}

type GetChatCostSummaryRow struct {
	TotalCostMicros          int64 `db:"total_cost_micros" json:"total_cost_micros"`
	PricedMessageCount       int64 `db:"priced_message_count" json:"priced_message_count"`
	UnpricedMessageCount     int64 `db:"unpriced_message_count" json:"unpriced_message_count"`
	TotalInputTokens         int64 `db:"total_input_tokens" json:"total_input_tokens"`
	TotalOutputTokens        int64 `db:"total_output_tokens" json:"total_output_tokens"`
	TotalCacheReadTokens     int64 `db:"total_cache_read_tokens" json:"total_cache_read_tokens"`
	TotalCacheCreationTokens int64 `db:"total_cache_creation_tokens" json:"total_cache_creation_tokens"`
}

// Aggregate cost summary for a single user within a date range.
// Only counts assistant-role messages.
func (q *Queries) GetChatCostSummary(ctx context.Context, arg GetChatCostSummaryParams) (GetChatCostSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getChatCostSummary, arg.OwnerID, arg.StartDate, arg.EndDate)
	var i GetChatCostSummaryRow
	err := row.Scan(
		&i.TotalCostMicros,
		&i.PricedMessageCount,
		&i.UnpricedMessageCount,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
		&i.TotalCacheReadTokens,
		&i.TotalCacheCreationTokens,
	)
	return i, err
}

const getChatDiffStatusByChatID = `-- name: GetChatDiffStatusByChatID :one
SELECT
    chat_id, url, pull_request_state, changes_requested, additions, deletions, changed_files, refreshed_at, stale_at, created_at, updated_at, git_branch, git_remote_origin, pull_request_title, pull_request_draft, author_login, author_avatar_url, base_branch, pr_number, commits, approved, reviewer_count, head_branch
FROM
    chat_diff_statuses
WHERE
    chat_id = $1::uuid
`

func (q *Queries) GetChatDiffStatusByChatID(ctx context.Context, chatID uuid.UUID) (ChatDiffStatus, error) {
	row := q.db.QueryRowContext(ctx, getChatDiffStatusByChatID, chatID)
	var i ChatDiffStatus
	err := row.Scan(
		&i.ChatID,
		&i.Url,
		&i.PullRequestState,
		&i.ChangesRequested,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.RefreshedAt,
		&i.StaleAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GitBranch,
		&i.GitRemoteOrigin,
		&i.PullRequestTitle,
		&i.PullRequestDraft,
		&i.AuthorLogin,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.PrNumber,
		&i.Commits,
		&i.Approved,
		&i.ReviewerCount,
		&i.HeadBranch,
	)
	return i, err
}

const getChatDiffStatusesByChatIDs = `-- name: GetChatDiffStatusesByChatIDs :many
SELECT
    chat_id, url, pull_request_state, changes_requested, additions, deletions, changed_files, refreshed_at, stale_at, created_at, updated_at, git_branch, git_remote_origin, pull_request_title, pull_request_draft, author_login, author_avatar_url, base_branch, pr_number, commits, approved, reviewer_count, head_branch
FROM
    chat_diff_statuses
WHERE
    chat_id = ANY($1::uuid[])
`

func (q *Queries) GetChatDiffStatusesByChatIDs(ctx context.Context, chatIds []uuid.UUID) ([]ChatDiffStatus, error) {
	rows, err := q.db.QueryContext(ctx, getChatDiffStatusesByChatIDs, pq.Array(chatIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatDiffStatus
	for rows.Next() {
		var i ChatDiffStatus
		if err := rows.Scan(
			&i.ChatID,
			&i.Url,
			&i.PullRequestState,
			&i.ChangesRequested,
			&i.Additions,
			&i.Deletions,
			&i.ChangedFiles,
			&i.RefreshedAt,
			&i.StaleAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GitBranch,
			&i.GitRemoteOrigin,
			&i.PullRequestTitle,
			&i.PullRequestDraft,
			&i.AuthorLogin,
			&i.AuthorAvatarUrl,
			&i.BaseBranch,
			&i.PrNumber,
			&i.Commits,
			&i.Approved,
			&i.ReviewerCount,
			&i.HeadBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessageByID = `-- name: GetChatMessageByID :one
SELECT
    id, chat_id, model_config_id, created_at, role, content, visibility, input_tokens, output_tokens, total_tokens, reasoning_tokens, cache_creation_tokens, cache_read_tokens, context_limit, compressed, created_by, content_version, total_cost_micros, runtime_ms, deleted
FROM
    chat_messages
WHERE
    id = $1::bigint
    AND deleted = false
`

func (q *Queries) GetChatMessageByID(ctx context.Context, id int64) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, getChatMessageByID, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.ModelConfigID,
		&i.CreatedAt,
		&i.Role,
		&i.Content,
		&i.Visibility,
		&i.InputTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.ReasoningTokens,
		&i.CacheCreationTokens,
		&i.CacheReadTokens,
		&i.ContextLimit,
		&i.Compressed,
		&i.CreatedBy,
		&i.ContentVersion,
		&i.TotalCostMicros,
		&i.RuntimeMs,
		&i.Deleted,
	)
	return i, err
}

const getChatMessagesByChatID = `-- name: GetChatMessagesByChatID :many
SELECT
    id, chat_id, model_config_id, created_at, role, content, visibility, input_tokens, output_tokens, total_tokens, reasoning_tokens, cache_creation_tokens, cache_read_tokens, context_limit, compressed, created_by, content_version, total_cost_micros, runtime_ms, deleted
FROM
    chat_messages
WHERE
    chat_id = $1::uuid
    AND id > $2::bigint
    AND visibility IN ('user', 'both')
    AND deleted = false
ORDER BY
    created_at ASC
`

type GetChatMessagesByChatIDParams struct {
	ChatID  uuid.UUID `db:"chat_id" json:"chat_id"`
	AfterID int64     `db:"after_id" json:"after_id"`
}

func (q *Queries) GetChatMessagesByChatID(ctx context.Context, arg GetChatMessagesByChatIDParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getChatMessagesByChatID, arg.ChatID, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.ModelConfigID,
			&i.CreatedAt,
			&i.Role,
			&i.Content,
			&i.Visibility,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.ReasoningTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.ContextLimit,
			&i.Compressed,
			&i.CreatedBy,
			&i.ContentVersion,
			&i.TotalCostMicros,
			&i.RuntimeMs,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessagesByChatIDDescPaginated = `-- name: GetChatMessagesByChatIDDescPaginated :many
SELECT
    id, chat_id, model_config_id, created_at, role, content, visibility, input_tokens, output_tokens, total_tokens, reasoning_tokens, cache_creation_tokens, cache_read_tokens, context_limit, compressed, created_by, content_version, total_cost_micros, runtime_ms, deleted
FROM
    chat_messages
WHERE
    chat_id = $1::uuid
    AND CASE
        WHEN $2::bigint > 0 THEN id < $2::bigint
        ELSE true
    END
    AND visibility IN ('user', 'both')
    AND deleted = false
ORDER BY
    id DESC
LIMIT
    COALESCE(NULLIF($3::int, 0), 50)
`

type GetChatMessagesByChatIDDescPaginatedParams struct {
	ChatID   uuid.UUID `db:"chat_id" json:"chat_id"`
	BeforeID int64     `db:"before_id" json:"before_id"`
	LimitVal int32     `db:"limit_val" json:"limit_val"`
}

func (q *Queries) GetChatMessagesByChatIDDescPaginated(ctx context.Context, arg GetChatMessagesByChatIDDescPaginatedParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getChatMessagesByChatIDDescPaginated, arg.ChatID, arg.BeforeID, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.ModelConfigID,
			&i.CreatedAt,
			&i.Role,
			&i.Content,
			&i.Visibility,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.ReasoningTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.ContextLimit,
			&i.Compressed,
			&i.CreatedBy,
			&i.ContentVersion,
			&i.TotalCostMicros,
			&i.RuntimeMs,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessagesForPromptByChatID = `-- name: GetChatMessagesForPromptByChatID :many
WITH latest_compressed_summary AS (
    SELECT
        id
    FROM
        chat_messages
    WHERE
        chat_id = $1::uuid
        AND compressed = TRUE
        AND deleted = false
        AND visibility = 'model'
    ORDER BY
        created_at DESC,
        id DESC
    LIMIT
        1
)
SELECT
    id, chat_id, model_config_id, created_at, role, content, visibility, input_tokens, output_tokens, total_tokens, reasoning_tokens, cache_creation_tokens, cache_read_tokens, context_limit, compressed, created_by, content_version, total_cost_micros, runtime_ms, deleted
FROM
    chat_messages
WHERE
    chat_id = $1::uuid
    AND visibility IN ('model', 'both')
    AND deleted = false
    AND (
        (
            role = 'system'
            AND compressed = FALSE
        )
        OR (
            compressed = FALSE
            AND (
                NOT EXISTS (
                    SELECT
                        1
                    FROM
                        latest_compressed_summary
                )
                OR id > (
                    SELECT
                        id
                    FROM
                        latest_compressed_summary
                )
            )
        )
        OR id = (
            SELECT
                id
            FROM
                latest_compressed_summary
        )
    )
ORDER BY
    created_at ASC,
    id ASC
`

func (q *Queries) GetChatMessagesForPromptByChatID(ctx context.Context, chatID uuid.UUID) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getChatMessagesForPromptByChatID, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.ModelConfigID,
			&i.CreatedAt,
			&i.Role,
			&i.Content,
			&i.Visibility,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.ReasoningTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.ContextLimit,
			&i.Compressed,
			&i.CreatedBy,
			&i.ContentVersion,
			&i.TotalCostMicros,
			&i.RuntimeMs,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatQueuedMessages = `-- name: GetChatQueuedMessages :many
SELECT id, chat_id, content, created_at FROM chat_queued_messages
WHERE chat_id = $1
ORDER BY id ASC
`

func (q *Queries) GetChatQueuedMessages(ctx context.Context, chatID uuid.UUID) ([]ChatQueuedMessage, error) {
	rows, err := q.db.QueryContext(ctx, getChatQueuedMessages, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatQueuedMessage
	for rows.Next() {
		var i ChatQueuedMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatUsageLimitConfig = `-- name: GetChatUsageLimitConfig :one
SELECT id, singleton, enabled, default_limit_micros, period, created_at, updated_at FROM chat_usage_limit_config WHERE singleton = TRUE LIMIT 1
`

func (q *Queries) GetChatUsageLimitConfig(ctx context.Context) (ChatUsageLimitConfig, error) {
	row := q.db.QueryRowContext(ctx, getChatUsageLimitConfig)
	var i ChatUsageLimitConfig
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.Enabled,
		&i.DefaultLimitMicros,
		&i.Period,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatUsageLimitGroupOverride = `-- name: GetChatUsageLimitGroupOverride :one
SELECT id AS group_id, chat_spend_limit_micros AS spend_limit_micros
FROM groups
WHERE id = $1::uuid AND chat_spend_limit_micros IS NOT NULL
`

type GetChatUsageLimitGroupOverrideRow struct {
	GroupID          uuid.UUID     `db:"group_id" json:"group_id"`
	SpendLimitMicros sql.NullInt64 `db:"spend_limit_micros" json:"spend_limit_micros"`
}

func (q *Queries) GetChatUsageLimitGroupOverride(ctx context.Context, groupID uuid.UUID) (GetChatUsageLimitGroupOverrideRow, error) {
	row := q.db.QueryRowContext(ctx, getChatUsageLimitGroupOverride, groupID)
	var i GetChatUsageLimitGroupOverrideRow
	err := row.Scan(&i.GroupID, &i.SpendLimitMicros)
	return i, err
}

const getChatUsageLimitUserOverride = `-- name: GetChatUsageLimitUserOverride :one
SELECT id AS user_id, chat_spend_limit_micros AS spend_limit_micros
FROM users
WHERE id = $1::uuid AND chat_spend_limit_micros IS NOT NULL
`

type GetChatUsageLimitUserOverrideRow struct {
	UserID           uuid.UUID     `db:"user_id" json:"user_id"`
	SpendLimitMicros sql.NullInt64 `db:"spend_limit_micros" json:"spend_limit_micros"`
}

func (q *Queries) GetChatUsageLimitUserOverride(ctx context.Context, userID uuid.UUID) (GetChatUsageLimitUserOverrideRow, error) {
	row := q.db.QueryRowContext(ctx, getChatUsageLimitUserOverride, userID)
	var i GetChatUsageLimitUserOverrideRow
	err := row.Scan(&i.UserID, &i.SpendLimitMicros)
	return i, err
}

const getChats = `-- name: GetChats :many
SELECT
    id, owner_id, workspace_id, title, status, worker_id, started_at, heartbeat_at, created_at, updated_at, parent_chat_id, root_chat_id, last_model_config_id, archived, last_error, mode, mcp_server_ids
FROM
    chats
WHERE
    CASE
        WHEN $1 :: uuid != '00000000-0000-0000-0000-000000000000'::uuid THEN chats.owner_id = $1
        ELSE true
    END
    AND CASE
        WHEN $2 :: boolean IS NULL THEN true
        ELSE chats.archived = $2 :: boolean
    END
    AND CASE
        -- This allows using the last element on a page as effectively a cursor.
        -- This is an important option for scripts that need to paginate without
        -- duplicating or missing data.
        WHEN $3 :: uuid != '00000000-0000-0000-0000-000000000000'::uuid THEN (
            -- The pagination cursor is the last ID of the previous page.
            -- The query is ordered by the updated_at field, so select all
            -- rows before the cursor.
            (updated_at, id) < (
                SELECT
                    updated_at, id
                FROM
                    chats
                WHERE
                    id = $3
            )
        )
        ELSE true
    END
    -- Authorize Filter clause will be injected below in GetAuthorizedChats
    -- @authorize_filter
ORDER BY
    -- Deterministic and consistent ordering of all rows, even if they share
    -- a timestamp. This is to ensure consistent pagination.
    (updated_at, id) DESC OFFSET $4
LIMIT
    -- The chat list is unbounded and expected to grow large.
    -- Default to 50 to prevent accidental excessively large queries.
    COALESCE(NULLIF($5 :: int, 0), 50)
`

type GetChatsParams struct {
	OwnerID   uuid.UUID    `db:"owner_id" json:"owner_id"`
	Archived  sql.NullBool `db:"archived" json:"archived"`
	AfterID   uuid.UUID    `db:"after_id" json:"after_id"`
	OffsetOpt int32        `db:"offset_opt" json:"offset_opt"`
	LimitOpt  int32        `db:"limit_opt" json:"limit_opt"`
}

func (q *Queries) GetChats(ctx context.Context, arg GetChatsParams) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, getChats,
		arg.OwnerID,
		arg.Archived,
		arg.AfterID,
		arg.OffsetOpt,
		arg.LimitOpt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.WorkspaceID,
			&i.Title,
			&i.Status,
			&i.WorkerID,
			&i.StartedAt,
			&i.HeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentChatID,
			&i.RootChatID,
			&i.LastModelConfigID,
			&i.Archived,
			&i.LastError,
			&i.Mode,
			pq.Array(&i.MCPServerIDs),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastChatMessageByRole = `-- name: GetLastChatMessageByRole :one
SELECT
    id, chat_id, model_config_id, created_at, role, content, visibility, input_tokens, output_tokens, total_tokens, reasoning_tokens, cache_creation_tokens, cache_read_tokens, context_limit, compressed, created_by, content_version, total_cost_micros, runtime_ms, deleted
FROM
    chat_messages
WHERE
    chat_id = $1::uuid
    AND role = $2::chat_message_role
    AND deleted = false
ORDER BY
    created_at DESC, id DESC
LIMIT
    1
`

type GetLastChatMessageByRoleParams struct {
	ChatID uuid.UUID       `db:"chat_id" json:"chat_id"`
	Role   ChatMessageRole `db:"role" json:"role"`
}

func (q *Queries) GetLastChatMessageByRole(ctx context.Context, arg GetLastChatMessageByRoleParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, getLastChatMessageByRole, arg.ChatID, arg.Role)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.ModelConfigID,
		&i.CreatedAt,
		&i.Role,
		&i.Content,
		&i.Visibility,
		&i.InputTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.ReasoningTokens,
		&i.CacheCreationTokens,
		&i.CacheReadTokens,
		&i.ContextLimit,
		&i.Compressed,
		&i.CreatedBy,
		&i.ContentVersion,
		&i.TotalCostMicros,
		&i.RuntimeMs,
		&i.Deleted,
	)
	return i, err
}

const getStaleChats = `-- name: GetStaleChats :many
SELECT
    id, owner_id, workspace_id, title, status, worker_id, started_at, heartbeat_at, created_at, updated_at, parent_chat_id, root_chat_id, last_model_config_id, archived, last_error, mode, mcp_server_ids
FROM
    chats
WHERE
    status = 'running'::chat_status
    AND heartbeat_at < $1::timestamptz
`

// Find chats that appear stuck (running but heartbeat has expired).
// Used for recovery after coderd crashes or long hangs.
func (q *Queries) GetStaleChats(ctx context.Context, staleThreshold time.Time) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, getStaleChats, staleThreshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.WorkspaceID,
			&i.Title,
			&i.Status,
			&i.WorkerID,
			&i.StartedAt,
			&i.HeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentChatID,
			&i.RootChatID,
			&i.LastModelConfigID,
			&i.Archived,
			&i.LastError,
			&i.Mode,
			pq.Array(&i.MCPServerIDs),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserChatSpendInPeriod = `-- name: GetUserChatSpendInPeriod :one
SELECT COALESCE(SUM(cm.total_cost_micros), 0)::bigint AS total_spend_micros
FROM chat_messages cm
JOIN chats c ON c.id = cm.chat_id
WHERE c.owner_id = $1::uuid
  AND cm.created_at >= $2::timestamptz
  AND cm.created_at < $3::timestamptz
  AND cm.total_cost_micros IS NOT NULL
`

type GetUserChatSpendInPeriodParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	StartTime time.Time `db:"start_time" json:"start_time"`
	EndTime   time.Time `db:"end_time" json:"end_time"`
}

func (q *Queries) GetUserChatSpendInPeriod(ctx context.Context, arg GetUserChatSpendInPeriodParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserChatSpendInPeriod, arg.UserID, arg.StartTime, arg.EndTime)
	var total_spend_micros int64
	err := row.Scan(&total_spend_micros)
	return total_spend_micros, err
}

const getUserGroupSpendLimit = `-- name: GetUserGroupSpendLimit :one
SELECT COALESCE(MIN(g.chat_spend_limit_micros), -1)::bigint AS limit_micros
FROM groups g
JOIN group_members_expanded gme ON gme.group_id = g.id
WHERE gme.user_id = $1::uuid
  AND g.chat_spend_limit_micros IS NOT NULL
`

// Returns the minimum (most restrictive) group limit for a user.
// Returns -1 if the user has no group limits applied.
func (q *Queries) GetUserGroupSpendLimit(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserGroupSpendLimit, userID)
	var limit_micros int64
	err := row.Scan(&limit_micros)
	return limit_micros, err
}

const insertChat = `-- name: InsertChat :one
INSERT INTO chats (
    owner_id,
    workspace_id,
    parent_chat_id,
    root_chat_id,
    last_model_config_id,
    title,
    mode,
    mcp_server_ids
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5::uuid,
    $6::text,
    $7::chat_mode,
    COALESCE($8::uuid[], '{}'::uuid[])
)
RETURNING
    id, owner_id, workspace_id, title, status, worker_id, started_at, heartbeat_at, created_at, updated_at, parent_chat_id, root_chat_id, last_model_config_id, archived, last_error, mode, mcp_server_ids
`

type InsertChatParams struct {
	OwnerID           uuid.UUID     `db:"owner_id" json:"owner_id"`
	WorkspaceID       uuid.NullUUID `db:"workspace_id" json:"workspace_id"`
	ParentChatID      uuid.NullUUID `db:"parent_chat_id" json:"parent_chat_id"`
	RootChatID        uuid.NullUUID `db:"root_chat_id" json:"root_chat_id"`
	LastModelConfigID uuid.UUID     `db:"last_model_config_id" json:"last_model_config_id"`
	Title             string        `db:"title" json:"title"`
	Mode              NullChatMode  `db:"mode" json:"mode"`
	MCPServerIDs      []uuid.UUID   `db:"mcp_server_ids" json:"mcp_server_ids"`
}

func (q *Queries) InsertChat(ctx context.Context, arg InsertChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, insertChat,
		arg.OwnerID,
		arg.WorkspaceID,
		arg.ParentChatID,
		arg.RootChatID,
		arg.LastModelConfigID,
		arg.Title,
		arg.Mode,
		pq.Array(arg.MCPServerIDs),
	)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.WorkspaceID,
		&i.Title,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentChatID,
		&i.RootChatID,
		&i.LastModelConfigID,
		&i.Archived,
		&i.LastError,
		&i.Mode,
		pq.Array(&i.MCPServerIDs),
	)
	return i, err
}

const insertChatMessages = `-- name: InsertChatMessages :many
WITH updated_chat AS (
    UPDATE
        chats
    SET
        last_model_config_id = (
            SELECT val
            FROM UNNEST($3::uuid[])
                WITH ORDINALITY AS t(val, ord)
            WHERE val != '00000000-0000-0000-0000-000000000000'::uuid
            ORDER BY ord DESC
            LIMIT 1
        )
    WHERE
        id = $1::uuid
        AND EXISTS (
            SELECT 1
            FROM UNNEST($3::uuid[])
            WHERE unnest != '00000000-0000-0000-0000-000000000000'::uuid
        )
        AND chats.last_model_config_id IS DISTINCT FROM (
            SELECT val
            FROM UNNEST($3::uuid[])
                WITH ORDINALITY AS t(val, ord)
            WHERE val != '00000000-0000-0000-0000-000000000000'::uuid
            ORDER BY ord DESC
            LIMIT 1
        )
)
INSERT INTO chat_messages (
    chat_id,
    created_by,
    model_config_id,
    role,
    content,
    content_version,
    visibility,
    input_tokens,
    output_tokens,
    total_tokens,
    reasoning_tokens,
    cache_creation_tokens,
    cache_read_tokens,
    context_limit,
    compressed,
    total_cost_micros,
    runtime_ms
)
SELECT
    $1::uuid,
    NULLIF(UNNEST($2::uuid[]), '00000000-0000-0000-0000-000000000000'::uuid),
    NULLIF(UNNEST($3::uuid[]), '00000000-0000-0000-0000-000000000000'::uuid),
    UNNEST($4::chat_message_role[]),
    UNNEST($5::text[])::jsonb,
    UNNEST($6::smallint[]),
    UNNEST($7::chat_message_visibility[]),
    NULLIF(UNNEST($8::bigint[]), 0),
    NULLIF(UNNEST($9::bigint[]), 0),
    NULLIF(UNNEST($10::bigint[]), 0),
    NULLIF(UNNEST($11::bigint[]), 0),
    NULLIF(UNNEST($12::bigint[]), 0),
    NULLIF(UNNEST($13::bigint[]), 0),
    NULLIF(UNNEST($14::bigint[]), 0),
    UNNEST($15::boolean[]),
    NULLIF(UNNEST($16::bigint[]), 0),
    NULLIF(UNNEST($17::bigint[]), 0)
RETURNING
    id, chat_id, model_config_id, created_at, role, content, visibility, input_tokens, output_tokens, total_tokens, reasoning_tokens, cache_creation_tokens, cache_read_tokens, context_limit, compressed, created_by, content_version, total_cost_micros, runtime_ms, deleted
`

type InsertChatMessagesParams struct {
	ChatID              uuid.UUID               `db:"chat_id" json:"chat_id"`
	CreatedBy           []uuid.UUID             `db:"created_by" json:"created_by"`
	ModelConfigID       []uuid.UUID             `db:"model_config_id" json:"model_config_id"`
	Role                []ChatMessageRole       `db:"role" json:"role"`
	Content             []string                `db:"content" json:"content"`
	ContentVersion      []int16                 `db:"content_version" json:"content_version"`
	Visibility          []ChatMessageVisibility `db:"visibility" json:"visibility"`
	InputTokens         []int64                 `db:"input_tokens" json:"input_tokens"`
	OutputTokens        []int64                 `db:"output_tokens" json:"output_tokens"`
	TotalTokens         []int64                 `db:"total_tokens" json:"total_tokens"`
	ReasoningTokens     []int64                 `db:"reasoning_tokens" json:"reasoning_tokens"`
	CacheCreationTokens []int64                 `db:"cache_creation_tokens" json:"cache_creation_tokens"`
	CacheReadTokens     []int64                 `db:"cache_read_tokens" json:"cache_read_tokens"`
	ContextLimit        []int64                 `db:"context_limit" json:"context_limit"`
	Compressed          []bool                  `db:"compressed" json:"compressed"`
	TotalCostMicros     []int64                 `db:"total_cost_micros" json:"total_cost_micros"`
	RuntimeMs           []int64                 `db:"runtime_ms" json:"runtime_ms"`
}

func (q *Queries) InsertChatMessages(ctx context.Context, arg InsertChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, insertChatMessages,
		arg.ChatID,
		pq.Array(arg.CreatedBy),
		pq.Array(arg.ModelConfigID),
		pq.Array(arg.Role),
		pq.Array(arg.Content),
		pq.Array(arg.ContentVersion),
		pq.Array(arg.Visibility),
		pq.Array(arg.InputTokens),
		pq.Array(arg.OutputTokens),
		pq.Array(arg.TotalTokens),
		pq.Array(arg.ReasoningTokens),
		pq.Array(arg.CacheCreationTokens),
		pq.Array(arg.CacheReadTokens),
		pq.Array(arg.ContextLimit),
		pq.Array(arg.Compressed),
		pq.Array(arg.TotalCostMicros),
		pq.Array(arg.RuntimeMs),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.ModelConfigID,
			&i.CreatedAt,
			&i.Role,
			&i.Content,
			&i.Visibility,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.ReasoningTokens,
			&i.CacheCreationTokens,
			&i.CacheReadTokens,
			&i.ContextLimit,
			&i.Compressed,
			&i.CreatedBy,
			&i.ContentVersion,
			&i.TotalCostMicros,
			&i.RuntimeMs,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChatQueuedMessage = `-- name: InsertChatQueuedMessage :one
INSERT INTO chat_queued_messages (chat_id, content)
VALUES ($1, $2)
RETURNING id, chat_id, content, created_at
`

type InsertChatQueuedMessageParams struct {
	ChatID  uuid.UUID       `db:"chat_id" json:"chat_id"`
	Content json.RawMessage `db:"content" json:"content"`
}

func (q *Queries) InsertChatQueuedMessage(ctx context.Context, arg InsertChatQueuedMessageParams) (ChatQueuedMessage, error) {
	row := q.db.QueryRowContext(ctx, insertChatQueuedMessage, arg.ChatID, arg.Content)
	var i ChatQueuedMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listChatUsageLimitGroupOverrides = `-- name: ListChatUsageLimitGroupOverrides :many
SELECT
    g.id AS group_id,
    g.name AS group_name,
    g.display_name AS group_display_name,
    g.avatar_url AS group_avatar_url,
    g.chat_spend_limit_micros AS spend_limit_micros,
    (SELECT COUNT(*)
        FROM group_members_expanded gme
        WHERE gme.group_id = g.id
          AND gme.user_is_system = FALSE) AS member_count
FROM groups g
WHERE g.chat_spend_limit_micros IS NOT NULL
ORDER BY g.name ASC
`

type ListChatUsageLimitGroupOverridesRow struct {
	GroupID          uuid.UUID     `db:"group_id" json:"group_id"`
	GroupName        string        `db:"group_name" json:"group_name"`
	GroupDisplayName string        `db:"group_display_name" json:"group_display_name"`
	GroupAvatarUrl   string        `db:"group_avatar_url" json:"group_avatar_url"`
	SpendLimitMicros sql.NullInt64 `db:"spend_limit_micros" json:"spend_limit_micros"`
	MemberCount      int64         `db:"member_count" json:"member_count"`
}

func (q *Queries) ListChatUsageLimitGroupOverrides(ctx context.Context) ([]ListChatUsageLimitGroupOverridesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatUsageLimitGroupOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatUsageLimitGroupOverridesRow
	for rows.Next() {
		var i ListChatUsageLimitGroupOverridesRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.GroupDisplayName,
			&i.GroupAvatarUrl,
			&i.SpendLimitMicros,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatUsageLimitOverrides = `-- name: ListChatUsageLimitOverrides :many
SELECT u.id AS user_id, u.username, u.name, u.avatar_url,
       u.chat_spend_limit_micros AS spend_limit_micros
FROM users u
WHERE u.chat_spend_limit_micros IS NOT NULL
ORDER BY u.username ASC
`

type ListChatUsageLimitOverridesRow struct {
	UserID           uuid.UUID     `db:"user_id" json:"user_id"`
	Username         string        `db:"username" json:"username"`
	Name             string        `db:"name" json:"name"`
	AvatarURL        string        `db:"avatar_url" json:"avatar_url"`
	SpendLimitMicros sql.NullInt64 `db:"spend_limit_micros" json:"spend_limit_micros"`
}

func (q *Queries) ListChatUsageLimitOverrides(ctx context.Context) ([]ListChatUsageLimitOverridesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatUsageLimitOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatUsageLimitOverridesRow
	for rows.Next() {
		var i ListChatUsageLimitOverridesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Name,
			&i.AvatarURL,
			&i.SpendLimitMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const popNextQueuedMessage = `-- name: PopNextQueuedMessage :one
DELETE FROM chat_queued_messages
WHERE id = (
    SELECT cqm.id FROM chat_queued_messages cqm
    WHERE cqm.chat_id = $1
    ORDER BY cqm.id ASC
    LIMIT 1
)
RETURNING id, chat_id, content, created_at
`

func (q *Queries) PopNextQueuedMessage(ctx context.Context, chatID uuid.UUID) (ChatQueuedMessage, error) {
	row := q.db.QueryRowContext(ctx, popNextQueuedMessage, chatID)
	var i ChatQueuedMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const resolveUserChatSpendLimit = `-- name: ResolveUserChatSpendLimit :one
SELECT CASE
    -- If limits are disabled, return -1.
    WHEN NOT cfg.enabled THEN -1
    -- Individual override takes priority.
    WHEN u.chat_spend_limit_micros IS NOT NULL THEN u.chat_spend_limit_micros
    -- Group limit (minimum across all user's groups) is next.
    WHEN gl.limit_micros IS NOT NULL THEN gl.limit_micros
    -- Fall back to global default.
    ELSE cfg.default_limit_micros
END::bigint AS effective_limit_micros
FROM chat_usage_limit_config cfg
CROSS JOIN users u
LEFT JOIN LATERAL (
    SELECT MIN(g.chat_spend_limit_micros) AS limit_micros
    FROM groups g
    JOIN group_members_expanded gme ON gme.group_id = g.id
    WHERE gme.user_id = $1::uuid
      AND g.chat_spend_limit_micros IS NOT NULL
) gl ON TRUE
WHERE u.id = $1::uuid
LIMIT 1
`

// Resolves the effective spend limit for a user using the hierarchy:
// 1. Individual user override (highest priority)
// 2. Minimum group limit across all user's groups
// 3. Global default from config
// Returns -1 if limits are not enabled.
func (q *Queries) ResolveUserChatSpendLimit(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, resolveUserChatSpendLimit, userID)
	var effective_limit_micros int64
	err := row.Scan(&effective_limit_micros)
	return effective_limit_micros, err
}

const softDeleteChatMessageByID = `-- name: SoftDeleteChatMessageByID :exec
UPDATE
    chat_messages
SET
    deleted = true
WHERE
    id = $1::bigint
`

func (q *Queries) SoftDeleteChatMessageByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteChatMessageByID, id)
	return err
}

const softDeleteChatMessagesAfterID = `-- name: SoftDeleteChatMessagesAfterID :exec
UPDATE
    chat_messages
SET
    deleted = true
WHERE
    chat_id = $1::uuid
    AND id > $2::bigint
`

type SoftDeleteChatMessagesAfterIDParams struct {
	ChatID  uuid.UUID `db:"chat_id" json:"chat_id"`
	AfterID int64     `db:"after_id" json:"after_id"`
}

func (q *Queries) SoftDeleteChatMessagesAfterID(ctx context.Context, arg SoftDeleteChatMessagesAfterIDParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteChatMessagesAfterID, arg.ChatID, arg.AfterID)
	return err
}

const unarchiveChatByID = `-- name: UnarchiveChatByID :exec
UPDATE chats SET archived = false, updated_at = NOW() WHERE id = $1::uuid
`

func (q *Queries) UnarchiveChatByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, unarchiveChatByID, id)
	return err
}

const updateChatByID = `-- name: UpdateChatByID :one
UPDATE
    chats
SET
    title = $1::text,
    updated_at = NOW()
WHERE
    id = $2::uuid
RETURNING
    id, owner_id, workspace_id, title, status, worker_id, started_at, heartbeat_at, created_at, updated_at, parent_chat_id, root_chat_id, last_model_config_id, archived, last_error, mode, mcp_server_ids
`

type UpdateChatByIDParams struct {
	Title string    `db:"title" json:"title"`
	ID    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateChatByID(ctx context.Context, arg UpdateChatByIDParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, updateChatByID, arg.Title, arg.ID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.WorkspaceID,
		&i.Title,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentChatID,
		&i.RootChatID,
		&i.LastModelConfigID,
		&i.Archived,
		&i.LastError,
		&i.Mode,
		pq.Array(&i.MCPServerIDs),
	)
	return i, err
}

const updateChatHeartbeat = `-- name: UpdateChatHeartbeat :execrows
UPDATE
    chats
SET
    heartbeat_at = NOW()
WHERE
    id = $1::uuid
    AND worker_id = $2::uuid
    AND status = 'running'::chat_status
`

type UpdateChatHeartbeatParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	WorkerID uuid.UUID `db:"worker_id" json:"worker_id"`
}

// Bumps the heartbeat timestamp for a running chat so that other
// replicas know the worker is still alive.
func (q *Queries) UpdateChatHeartbeat(ctx context.Context, arg UpdateChatHeartbeatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateChatHeartbeat, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateChatMCPServerIDs = `-- name: UpdateChatMCPServerIDs :one
UPDATE
    chats
SET
    mcp_server_ids = $1::uuid[],
    updated_at = NOW()
WHERE
    id = $2::uuid
RETURNING
    id, owner_id, workspace_id, title, status, worker_id, started_at, heartbeat_at, created_at, updated_at, parent_chat_id, root_chat_id, last_model_config_id, archived, last_error, mode, mcp_server_ids
`

type UpdateChatMCPServerIDsParams struct {
	MCPServerIDs []uuid.UUID `db:"mcp_server_ids" json:"mcp_server_ids"`
	ID           uuid.UUID   `db:"id" json:"id"`
}

func (q *Queries) UpdateChatMCPServerIDs(ctx context.Context, arg UpdateChatMCPServerIDsParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, updateChatMCPServerIDs, pq.Array(arg.MCPServerIDs), arg.ID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.WorkspaceID,
		&i.Title,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentChatID,
		&i.RootChatID,
		&i.LastModelConfigID,
		&i.Archived,
		&i.LastError,
		&i.Mode,
		pq.Array(&i.MCPServerIDs),
	)
	return i, err
}

const updateChatMessageByID = `-- name: UpdateChatMessageByID :one
UPDATE
    chat_messages
SET
    model_config_id = COALESCE($1::uuid, model_config_id),
    content = $2::jsonb
WHERE
    id = $3::bigint
RETURNING
    id, chat_id, model_config_id, created_at, role, content, visibility, input_tokens, output_tokens, total_tokens, reasoning_tokens, cache_creation_tokens, cache_read_tokens, context_limit, compressed, created_by, content_version, total_cost_micros, runtime_ms, deleted
`

type UpdateChatMessageByIDParams struct {
	ModelConfigID uuid.NullUUID         `db:"model_config_id" json:"model_config_id"`
	Content       pqtype.NullRawMessage `db:"content" json:"content"`
	ID            int64                 `db:"id" json:"id"`
}

func (q *Queries) UpdateChatMessageByID(ctx context.Context, arg UpdateChatMessageByIDParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, updateChatMessageByID, arg.ModelConfigID, arg.Content, arg.ID)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.ModelConfigID,
		&i.CreatedAt,
		&i.Role,
		&i.Content,
		&i.Visibility,
		&i.InputTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.ReasoningTokens,
		&i.CacheCreationTokens,
		&i.CacheReadTokens,
		&i.ContextLimit,
		&i.Compressed,
		&i.CreatedBy,
		&i.ContentVersion,
		&i.TotalCostMicros,
		&i.RuntimeMs,
		&i.Deleted,
	)
	return i, err
}

const updateChatStatus = `-- name: UpdateChatStatus :one
UPDATE
    chats
SET
    status = $1::chat_status,
    worker_id = $2::uuid,
    started_at = $3::timestamptz,
    heartbeat_at = $4::timestamptz,
    last_error = $5::text,
    updated_at = NOW()
WHERE
    id = $6::uuid
RETURNING
    id, owner_id, workspace_id, title, status, worker_id, started_at, heartbeat_at, created_at, updated_at, parent_chat_id, root_chat_id, last_model_config_id, archived, last_error, mode, mcp_server_ids
`

type UpdateChatStatusParams struct {
	Status      ChatStatus     `db:"status" json:"status"`
	WorkerID    uuid.NullUUID  `db:"worker_id" json:"worker_id"`
	StartedAt   sql.NullTime   `db:"started_at" json:"started_at"`
	HeartbeatAt sql.NullTime   `db:"heartbeat_at" json:"heartbeat_at"`
	LastError   sql.NullString `db:"last_error" json:"last_error"`
	ID          uuid.UUID      `db:"id" json:"id"`
}

func (q *Queries) UpdateChatStatus(ctx context.Context, arg UpdateChatStatusParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, updateChatStatus,
		arg.Status,
		arg.WorkerID,
		arg.StartedAt,
		arg.HeartbeatAt,
		arg.LastError,
		arg.ID,
	)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.WorkspaceID,
		&i.Title,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentChatID,
		&i.RootChatID,
		&i.LastModelConfigID,
		&i.Archived,
		&i.LastError,
		&i.Mode,
		pq.Array(&i.MCPServerIDs),
	)
	return i, err
}

const updateChatWorkspace = `-- name: UpdateChatWorkspace :one
UPDATE
    chats
SET
    workspace_id = $1::uuid,
    updated_at = NOW()
WHERE
    id = $2::uuid
RETURNING
    id, owner_id, workspace_id, title, status, worker_id, started_at, heartbeat_at, created_at, updated_at, parent_chat_id, root_chat_id, last_model_config_id, archived, last_error, mode, mcp_server_ids
`

type UpdateChatWorkspaceParams struct {
	WorkspaceID uuid.NullUUID `db:"workspace_id" json:"workspace_id"`
	ID          uuid.UUID     `db:"id" json:"id"`
}

func (q *Queries) UpdateChatWorkspace(ctx context.Context, arg UpdateChatWorkspaceParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, updateChatWorkspace, arg.WorkspaceID, arg.ID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.WorkspaceID,
		&i.Title,
		&i.Status,
		&i.WorkerID,
		&i.StartedAt,
		&i.HeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentChatID,
		&i.RootChatID,
		&i.LastModelConfigID,
		&i.Archived,
		&i.LastError,
		&i.Mode,
		pq.Array(&i.MCPServerIDs),
	)
	return i, err
}

const upsertChatDiffStatus = `-- name: UpsertChatDiffStatus :one
INSERT INTO chat_diff_statuses (
    chat_id,
    url,
    pull_request_state,
    pull_request_title,
    pull_request_draft,
    changes_requested,
    additions,
    deletions,
    changed_files,
    author_login,
    author_avatar_url,
    base_branch,
    head_branch,
    pr_number,
    commits,
    approved,
    reviewer_count,
    refreshed_at,
    stale_at
) VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::text,
    $5::boolean,
    $6::boolean,
    $7::integer,
    $8::integer,
    $9::integer,
    $10::text,
    $11::text,
    $12::text,
    $13::text,
    $14::integer,
    $15::integer,
    $16::boolean,
    $17::integer,
    $18::timestamptz,
    $19::timestamptz
)
ON CONFLICT (chat_id) DO UPDATE
SET
    url = EXCLUDED.url,
    pull_request_state = EXCLUDED.pull_request_state,
    pull_request_title = EXCLUDED.pull_request_title,
    pull_request_draft = EXCLUDED.pull_request_draft,
    changes_requested = EXCLUDED.changes_requested,
    additions = EXCLUDED.additions,
    deletions = EXCLUDED.deletions,
    changed_files = EXCLUDED.changed_files,
    author_login = EXCLUDED.author_login,
    author_avatar_url = EXCLUDED.author_avatar_url,
    base_branch = EXCLUDED.base_branch,
    head_branch = EXCLUDED.head_branch,
    pr_number = EXCLUDED.pr_number,
    commits = EXCLUDED.commits,
    approved = EXCLUDED.approved,
    reviewer_count = EXCLUDED.reviewer_count,
    refreshed_at = EXCLUDED.refreshed_at,
    stale_at = EXCLUDED.stale_at,
    updated_at = NOW()
RETURNING
    chat_id, url, pull_request_state, changes_requested, additions, deletions, changed_files, refreshed_at, stale_at, created_at, updated_at, git_branch, git_remote_origin, pull_request_title, pull_request_draft, author_login, author_avatar_url, base_branch, pr_number, commits, approved, reviewer_count, head_branch
`

type UpsertChatDiffStatusParams struct {
	ChatID           uuid.UUID      `db:"chat_id" json:"chat_id"`
	Url              sql.NullString `db:"url" json:"url"`
	PullRequestState sql.NullString `db:"pull_request_state" json:"pull_request_state"`
	PullRequestTitle string         `db:"pull_request_title" json:"pull_request_title"`
	PullRequestDraft bool           `db:"pull_request_draft" json:"pull_request_draft"`
	ChangesRequested bool           `db:"changes_requested" json:"changes_requested"`
	Additions        int32          `db:"additions" json:"additions"`
	Deletions        int32          `db:"deletions" json:"deletions"`
	ChangedFiles     int32          `db:"changed_files" json:"changed_files"`
	AuthorLogin      sql.NullString `db:"author_login" json:"author_login"`
	AuthorAvatarUrl  sql.NullString `db:"author_avatar_url" json:"author_avatar_url"`
	BaseBranch       sql.NullString `db:"base_branch" json:"base_branch"`
	HeadBranch       sql.NullString `db:"head_branch" json:"head_branch"`
	PrNumber         sql.NullInt32  `db:"pr_number" json:"pr_number"`
	Commits          sql.NullInt32  `db:"commits" json:"commits"`
	Approved         sql.NullBool   `db:"approved" json:"approved"`
	ReviewerCount    sql.NullInt32  `db:"reviewer_count" json:"reviewer_count"`
	RefreshedAt      time.Time      `db:"refreshed_at" json:"refreshed_at"`
	StaleAt          time.Time      `db:"stale_at" json:"stale_at"`
}

func (q *Queries) UpsertChatDiffStatus(ctx context.Context, arg UpsertChatDiffStatusParams) (ChatDiffStatus, error) {
	row := q.db.QueryRowContext(ctx, upsertChatDiffStatus,
		arg.ChatID,
		arg.Url,
		arg.PullRequestState,
		arg.PullRequestTitle,
		arg.PullRequestDraft,
		arg.ChangesRequested,
		arg.Additions,
		arg.Deletions,
		arg.ChangedFiles,
		arg.AuthorLogin,
		arg.AuthorAvatarUrl,
		arg.BaseBranch,
		arg.HeadBranch,
		arg.PrNumber,
		arg.Commits,
		arg.Approved,
		arg.ReviewerCount,
		arg.RefreshedAt,
		arg.StaleAt,
	)
	var i ChatDiffStatus
	err := row.Scan(
		&i.ChatID,
		&i.Url,
		&i.PullRequestState,
		&i.ChangesRequested,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.RefreshedAt,
		&i.StaleAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GitBranch,
		&i.GitRemoteOrigin,
		&i.PullRequestTitle,
		&i.PullRequestDraft,
		&i.AuthorLogin,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.PrNumber,
		&i.Commits,
		&i.Approved,
		&i.ReviewerCount,
		&i.HeadBranch,
	)
	return i, err
}

const upsertChatDiffStatusReference = `-- name: UpsertChatDiffStatusReference :one
INSERT INTO chat_diff_statuses (
    chat_id,
    url,
    git_branch,
    git_remote_origin,
    stale_at
) VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::text,
    $5::timestamptz
)
ON CONFLICT (chat_id) DO UPDATE
SET
    url = CASE
        WHEN EXCLUDED.url IS NOT NULL THEN EXCLUDED.url
        ELSE chat_diff_statuses.url
    END,
    git_branch = CASE
        WHEN EXCLUDED.git_branch != '' THEN EXCLUDED.git_branch
        ELSE chat_diff_statuses.git_branch
    END,
    git_remote_origin = CASE
        WHEN EXCLUDED.git_remote_origin != '' THEN EXCLUDED.git_remote_origin
        ELSE chat_diff_statuses.git_remote_origin
    END,
    stale_at = EXCLUDED.stale_at,
    updated_at = NOW()
RETURNING
    chat_id, url, pull_request_state, changes_requested, additions, deletions, changed_files, refreshed_at, stale_at, created_at, updated_at, git_branch, git_remote_origin, pull_request_title, pull_request_draft, author_login, author_avatar_url, base_branch, pr_number, commits, approved, reviewer_count, head_branch
`

type UpsertChatDiffStatusReferenceParams struct {
	ChatID          uuid.UUID      `db:"chat_id" json:"chat_id"`
	Url             sql.NullString `db:"url" json:"url"`
	GitBranch       string         `db:"git_branch" json:"git_branch"`
	GitRemoteOrigin string         `db:"git_remote_origin" json:"git_remote_origin"`
	StaleAt         time.Time      `db:"stale_at" json:"stale_at"`
}

func (q *Queries) UpsertChatDiffStatusReference(ctx context.Context, arg UpsertChatDiffStatusReferenceParams) (ChatDiffStatus, error) {
	row := q.db.QueryRowContext(ctx, upsertChatDiffStatusReference,
		arg.ChatID,
		arg.Url,
		arg.GitBranch,
		arg.GitRemoteOrigin,
		arg.StaleAt,
	)
	var i ChatDiffStatus
	err := row.Scan(
		&i.ChatID,
		&i.Url,
		&i.PullRequestState,
		&i.ChangesRequested,
		&i.Additions,
		&i.Deletions,
		&i.ChangedFiles,
		&i.RefreshedAt,
		&i.StaleAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GitBranch,
		&i.GitRemoteOrigin,
		&i.PullRequestTitle,
		&i.PullRequestDraft,
		&i.AuthorLogin,
		&i.AuthorAvatarUrl,
		&i.BaseBranch,
		&i.PrNumber,
		&i.Commits,
		&i.Approved,
		&i.ReviewerCount,
		&i.HeadBranch,
	)
	return i, err
}

const upsertChatUsageLimitConfig = `-- name: UpsertChatUsageLimitConfig :one
INSERT INTO chat_usage_limit_config (singleton, enabled, default_limit_micros, period, updated_at)
VALUES (TRUE, $1::boolean, $2::bigint, $3::text, NOW())
ON CONFLICT (singleton) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    default_limit_micros = EXCLUDED.default_limit_micros,
    period = EXCLUDED.period,
    updated_at = NOW()
RETURNING id, singleton, enabled, default_limit_micros, period, created_at, updated_at
`

type UpsertChatUsageLimitConfigParams struct {
	Enabled            bool   `db:"enabled" json:"enabled"`
	DefaultLimitMicros int64  `db:"default_limit_micros" json:"default_limit_micros"`
	Period             string `db:"period" json:"period"`
}

func (q *Queries) UpsertChatUsageLimitConfig(ctx context.Context, arg UpsertChatUsageLimitConfigParams) (ChatUsageLimitConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertChatUsageLimitConfig, arg.Enabled, arg.DefaultLimitMicros, arg.Period)
	var i ChatUsageLimitConfig
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.Enabled,
		&i.DefaultLimitMicros,
		&i.Period,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertChatUsageLimitGroupOverride = `-- name: UpsertChatUsageLimitGroupOverride :one
UPDATE groups
SET chat_spend_limit_micros = $1::bigint
WHERE id = $2::uuid
RETURNING id AS group_id, name, display_name, avatar_url, chat_spend_limit_micros AS spend_limit_micros
`

type UpsertChatUsageLimitGroupOverrideParams struct {
	SpendLimitMicros int64     `db:"spend_limit_micros" json:"spend_limit_micros"`
	GroupID          uuid.UUID `db:"group_id" json:"group_id"`
}

type UpsertChatUsageLimitGroupOverrideRow struct {
	GroupID          uuid.UUID     `db:"group_id" json:"group_id"`
	Name             string        `db:"name" json:"name"`
	DisplayName      string        `db:"display_name" json:"display_name"`
	AvatarURL        string        `db:"avatar_url" json:"avatar_url"`
	SpendLimitMicros sql.NullInt64 `db:"spend_limit_micros" json:"spend_limit_micros"`
}

func (q *Queries) UpsertChatUsageLimitGroupOverride(ctx context.Context, arg UpsertChatUsageLimitGroupOverrideParams) (UpsertChatUsageLimitGroupOverrideRow, error) {
	row := q.db.QueryRowContext(ctx, upsertChatUsageLimitGroupOverride, arg.SpendLimitMicros, arg.GroupID)
	var i UpsertChatUsageLimitGroupOverrideRow
	err := row.Scan(
		&i.GroupID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarURL,
		&i.SpendLimitMicros,
	)
	return i, err
}

const upsertChatUsageLimitUserOverride = `-- name: UpsertChatUsageLimitUserOverride :one
UPDATE users
SET chat_spend_limit_micros = $1::bigint
WHERE id = $2::uuid
RETURNING id AS user_id, username, name, avatar_url, chat_spend_limit_micros AS spend_limit_micros
`

type UpsertChatUsageLimitUserOverrideParams struct {
	SpendLimitMicros int64     `db:"spend_limit_micros" json:"spend_limit_micros"`
	UserID           uuid.UUID `db:"user_id" json:"user_id"`
}

type UpsertChatUsageLimitUserOverrideRow struct {
	UserID           uuid.UUID     `db:"user_id" json:"user_id"`
	Username         string        `db:"username" json:"username"`
	Name             string        `db:"name" json:"name"`
	AvatarURL        string        `db:"avatar_url" json:"avatar_url"`
	SpendLimitMicros sql.NullInt64 `db:"spend_limit_micros" json:"spend_limit_micros"`
}

func (q *Queries) UpsertChatUsageLimitUserOverride(ctx context.Context, arg UpsertChatUsageLimitUserOverrideParams) (UpsertChatUsageLimitUserOverrideRow, error) {
	row := q.db.QueryRowContext(ctx, upsertChatUsageLimitUserOverride, arg.SpendLimitMicros, arg.UserID)
	var i UpsertChatUsageLimitUserOverrideRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Name,
		&i.AvatarURL,
		&i.SpendLimitMicros,
	)
	return i, err
}
