// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcpserverconfigs.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const cleanupDeletedMCPServerIDsFromChats = `-- name: CleanupDeletedMCPServerIDsFromChats :exec
UPDATE chats
SET mcp_server_ids = (
    SELECT COALESCE(array_agg(sid), '{}')
    FROM unnest(chats.mcp_server_ids) AS sid
    WHERE sid IN (SELECT id FROM mcp_server_configs)
)
WHERE mcp_server_ids != '{}'
  AND NOT (mcp_server_ids <@ COALESCE((SELECT array_agg(id) FROM mcp_server_configs), '{}'))
`

func (q *Queries) CleanupDeletedMCPServerIDsFromChats(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupDeletedMCPServerIDsFromChats)
	return err
}

const deleteMCPServerConfigByID = `-- name: DeleteMCPServerConfigByID :exec
DELETE FROM
    mcp_server_configs
WHERE
    id = $1::uuid
`

func (q *Queries) DeleteMCPServerConfigByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMCPServerConfigByID, id)
	return err
}

const deleteMCPServerUserToken = `-- name: DeleteMCPServerUserToken :exec
DELETE FROM
    mcp_server_user_tokens
WHERE
    mcp_server_config_id = $1::uuid
    AND user_id = $2::uuid
`

type DeleteMCPServerUserTokenParams struct {
	MCPServerConfigID uuid.UUID `db:"mcp_server_config_id" json:"mcp_server_config_id"`
	UserID            uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteMCPServerUserToken(ctx context.Context, arg DeleteMCPServerUserTokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteMCPServerUserToken, arg.MCPServerConfigID, arg.UserID)
	return err
}

const getEnabledMCPServerConfigs = `-- name: GetEnabledMCPServerConfigs :many
SELECT
    id, display_name, slug, description, icon_url, transport, url, auth_type, oauth2_client_id, oauth2_client_secret, oauth2_client_secret_key_id, oauth2_auth_url, oauth2_token_url, oauth2_scopes, api_key_header, api_key_value, api_key_value_key_id, custom_headers, custom_headers_key_id, tool_allow_list, tool_deny_list, availability, enabled, created_by, updated_by, created_at, updated_at
FROM
    mcp_server_configs
WHERE
    enabled = TRUE
ORDER BY
    display_name ASC
`

func (q *Queries) GetEnabledMCPServerConfigs(ctx context.Context) ([]MCPServerConfig, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledMCPServerConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MCPServerConfig
	for rows.Next() {
		var i MCPServerConfig
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Slug,
			&i.Description,
			&i.IconURL,
			&i.Transport,
			&i.Url,
			&i.AuthType,
			&i.OAuth2ClientID,
			&i.OAuth2ClientSecret,
			&i.OAuth2ClientSecretKeyID,
			&i.OAuth2AuthURL,
			&i.OAuth2TokenURL,
			&i.OAuth2Scopes,
			&i.APIKeyHeader,
			&i.APIKeyValue,
			&i.APIKeyValueKeyID,
			&i.CustomHeaders,
			&i.CustomHeadersKeyID,
			pq.Array(&i.ToolAllowList),
			pq.Array(&i.ToolDenyList),
			&i.Availability,
			&i.Enabled,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getForcedMCPServerConfigs = `-- name: GetForcedMCPServerConfigs :many
SELECT
    id, display_name, slug, description, icon_url, transport, url, auth_type, oauth2_client_id, oauth2_client_secret, oauth2_client_secret_key_id, oauth2_auth_url, oauth2_token_url, oauth2_scopes, api_key_header, api_key_value, api_key_value_key_id, custom_headers, custom_headers_key_id, tool_allow_list, tool_deny_list, availability, enabled, created_by, updated_by, created_at, updated_at
FROM
    mcp_server_configs
WHERE
    enabled = TRUE
    AND availability = 'force_on'
ORDER BY
    display_name ASC
`

func (q *Queries) GetForcedMCPServerConfigs(ctx context.Context) ([]MCPServerConfig, error) {
	rows, err := q.db.QueryContext(ctx, getForcedMCPServerConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MCPServerConfig
	for rows.Next() {
		var i MCPServerConfig
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Slug,
			&i.Description,
			&i.IconURL,
			&i.Transport,
			&i.Url,
			&i.AuthType,
			&i.OAuth2ClientID,
			&i.OAuth2ClientSecret,
			&i.OAuth2ClientSecretKeyID,
			&i.OAuth2AuthURL,
			&i.OAuth2TokenURL,
			&i.OAuth2Scopes,
			&i.APIKeyHeader,
			&i.APIKeyValue,
			&i.APIKeyValueKeyID,
			&i.CustomHeaders,
			&i.CustomHeadersKeyID,
			pq.Array(&i.ToolAllowList),
			pq.Array(&i.ToolDenyList),
			&i.Availability,
			&i.Enabled,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMCPServerConfigByID = `-- name: GetMCPServerConfigByID :one
SELECT
    id, display_name, slug, description, icon_url, transport, url, auth_type, oauth2_client_id, oauth2_client_secret, oauth2_client_secret_key_id, oauth2_auth_url, oauth2_token_url, oauth2_scopes, api_key_header, api_key_value, api_key_value_key_id, custom_headers, custom_headers_key_id, tool_allow_list, tool_deny_list, availability, enabled, created_by, updated_by, created_at, updated_at
FROM
    mcp_server_configs
WHERE
    id = $1::uuid
`

func (q *Queries) GetMCPServerConfigByID(ctx context.Context, id uuid.UUID) (MCPServerConfig, error) {
	row := q.db.QueryRowContext(ctx, getMCPServerConfigByID, id)
	var i MCPServerConfig
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Slug,
		&i.Description,
		&i.IconURL,
		&i.Transport,
		&i.Url,
		&i.AuthType,
		&i.OAuth2ClientID,
		&i.OAuth2ClientSecret,
		&i.OAuth2ClientSecretKeyID,
		&i.OAuth2AuthURL,
		&i.OAuth2TokenURL,
		&i.OAuth2Scopes,
		&i.APIKeyHeader,
		&i.APIKeyValue,
		&i.APIKeyValueKeyID,
		&i.CustomHeaders,
		&i.CustomHeadersKeyID,
		pq.Array(&i.ToolAllowList),
		pq.Array(&i.ToolDenyList),
		&i.Availability,
		&i.Enabled,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMCPServerConfigBySlug = `-- name: GetMCPServerConfigBySlug :one
SELECT
    id, display_name, slug, description, icon_url, transport, url, auth_type, oauth2_client_id, oauth2_client_secret, oauth2_client_secret_key_id, oauth2_auth_url, oauth2_token_url, oauth2_scopes, api_key_header, api_key_value, api_key_value_key_id, custom_headers, custom_headers_key_id, tool_allow_list, tool_deny_list, availability, enabled, created_by, updated_by, created_at, updated_at
FROM
    mcp_server_configs
WHERE
    slug = $1::text
`

func (q *Queries) GetMCPServerConfigBySlug(ctx context.Context, slug string) (MCPServerConfig, error) {
	row := q.db.QueryRowContext(ctx, getMCPServerConfigBySlug, slug)
	var i MCPServerConfig
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Slug,
		&i.Description,
		&i.IconURL,
		&i.Transport,
		&i.Url,
		&i.AuthType,
		&i.OAuth2ClientID,
		&i.OAuth2ClientSecret,
		&i.OAuth2ClientSecretKeyID,
		&i.OAuth2AuthURL,
		&i.OAuth2TokenURL,
		&i.OAuth2Scopes,
		&i.APIKeyHeader,
		&i.APIKeyValue,
		&i.APIKeyValueKeyID,
		&i.CustomHeaders,
		&i.CustomHeadersKeyID,
		pq.Array(&i.ToolAllowList),
		pq.Array(&i.ToolDenyList),
		&i.Availability,
		&i.Enabled,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMCPServerConfigs = `-- name: GetMCPServerConfigs :many
SELECT
    id, display_name, slug, description, icon_url, transport, url, auth_type, oauth2_client_id, oauth2_client_secret, oauth2_client_secret_key_id, oauth2_auth_url, oauth2_token_url, oauth2_scopes, api_key_header, api_key_value, api_key_value_key_id, custom_headers, custom_headers_key_id, tool_allow_list, tool_deny_list, availability, enabled, created_by, updated_by, created_at, updated_at
FROM
    mcp_server_configs
ORDER BY
    display_name ASC
`

func (q *Queries) GetMCPServerConfigs(ctx context.Context) ([]MCPServerConfig, error) {
	rows, err := q.db.QueryContext(ctx, getMCPServerConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MCPServerConfig
	for rows.Next() {
		var i MCPServerConfig
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Slug,
			&i.Description,
			&i.IconURL,
			&i.Transport,
			&i.Url,
			&i.AuthType,
			&i.OAuth2ClientID,
			&i.OAuth2ClientSecret,
			&i.OAuth2ClientSecretKeyID,
			&i.OAuth2AuthURL,
			&i.OAuth2TokenURL,
			&i.OAuth2Scopes,
			&i.APIKeyHeader,
			&i.APIKeyValue,
			&i.APIKeyValueKeyID,
			&i.CustomHeaders,
			&i.CustomHeadersKeyID,
			pq.Array(&i.ToolAllowList),
			pq.Array(&i.ToolDenyList),
			&i.Availability,
			&i.Enabled,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMCPServerConfigsByIDs = `-- name: GetMCPServerConfigsByIDs :many
SELECT
    id, display_name, slug, description, icon_url, transport, url, auth_type, oauth2_client_id, oauth2_client_secret, oauth2_client_secret_key_id, oauth2_auth_url, oauth2_token_url, oauth2_scopes, api_key_header, api_key_value, api_key_value_key_id, custom_headers, custom_headers_key_id, tool_allow_list, tool_deny_list, availability, enabled, created_by, updated_by, created_at, updated_at
FROM
    mcp_server_configs
WHERE
    id = ANY($1::uuid[])
ORDER BY
    display_name ASC
`

func (q *Queries) GetMCPServerConfigsByIDs(ctx context.Context, ids []uuid.UUID) ([]MCPServerConfig, error) {
	rows, err := q.db.QueryContext(ctx, getMCPServerConfigsByIDs, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MCPServerConfig
	for rows.Next() {
		var i MCPServerConfig
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Slug,
			&i.Description,
			&i.IconURL,
			&i.Transport,
			&i.Url,
			&i.AuthType,
			&i.OAuth2ClientID,
			&i.OAuth2ClientSecret,
			&i.OAuth2ClientSecretKeyID,
			&i.OAuth2AuthURL,
			&i.OAuth2TokenURL,
			&i.OAuth2Scopes,
			&i.APIKeyHeader,
			&i.APIKeyValue,
			&i.APIKeyValueKeyID,
			&i.CustomHeaders,
			&i.CustomHeadersKeyID,
			pq.Array(&i.ToolAllowList),
			pq.Array(&i.ToolDenyList),
			&i.Availability,
			&i.Enabled,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMCPServerUserToken = `-- name: GetMCPServerUserToken :one
SELECT
    id, mcp_server_config_id, user_id, access_token, access_token_key_id, refresh_token, refresh_token_key_id, token_type, expiry, created_at, updated_at
FROM
    mcp_server_user_tokens
WHERE
    mcp_server_config_id = $1::uuid
    AND user_id = $2::uuid
`

type GetMCPServerUserTokenParams struct {
	MCPServerConfigID uuid.UUID `db:"mcp_server_config_id" json:"mcp_server_config_id"`
	UserID            uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetMCPServerUserToken(ctx context.Context, arg GetMCPServerUserTokenParams) (MCPServerUserToken, error) {
	row := q.db.QueryRowContext(ctx, getMCPServerUserToken, arg.MCPServerConfigID, arg.UserID)
	var i MCPServerUserToken
	err := row.Scan(
		&i.ID,
		&i.MCPServerConfigID,
		&i.UserID,
		&i.AccessToken,
		&i.AccessTokenKeyID,
		&i.RefreshToken,
		&i.RefreshTokenKeyID,
		&i.TokenType,
		&i.Expiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMCPServerUserTokensByUserID = `-- name: GetMCPServerUserTokensByUserID :many
SELECT
    id, mcp_server_config_id, user_id, access_token, access_token_key_id, refresh_token, refresh_token_key_id, token_type, expiry, created_at, updated_at
FROM
    mcp_server_user_tokens
WHERE
    user_id = $1::uuid
`

func (q *Queries) GetMCPServerUserTokensByUserID(ctx context.Context, userID uuid.UUID) ([]MCPServerUserToken, error) {
	rows, err := q.db.QueryContext(ctx, getMCPServerUserTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MCPServerUserToken
	for rows.Next() {
		var i MCPServerUserToken
		if err := rows.Scan(
			&i.ID,
			&i.MCPServerConfigID,
			&i.UserID,
			&i.AccessToken,
			&i.AccessTokenKeyID,
			&i.RefreshToken,
			&i.RefreshTokenKeyID,
			&i.TokenType,
			&i.Expiry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMCPServerConfig = `-- name: InsertMCPServerConfig :one
INSERT INTO mcp_server_configs (
    display_name,
    slug,
    description,
    icon_url,
    transport,
    url,
    auth_type,
    oauth2_client_id,
    oauth2_client_secret,
    oauth2_client_secret_key_id,
    oauth2_auth_url,
    oauth2_token_url,
    oauth2_scopes,
    api_key_header,
    api_key_value,
    api_key_value_key_id,
    custom_headers,
    custom_headers_key_id,
    tool_allow_list,
    tool_deny_list,
    availability,
    enabled,
    created_by,
    updated_by
) VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    $6::text,
    $7::text,
    $8::text,
    $9::text,
    $10::text,
    $11::text,
    $12::text,
    $13::text,
    $14::text,
    $15::text,
    $16::text,
    $17::text,
    $18::text,
    $19::text[],
    $20::text[],
    $21::text,
    $22::boolean,
    $23::uuid,
    $24::uuid
)
RETURNING
    id, display_name, slug, description, icon_url, transport, url, auth_type, oauth2_client_id, oauth2_client_secret, oauth2_client_secret_key_id, oauth2_auth_url, oauth2_token_url, oauth2_scopes, api_key_header, api_key_value, api_key_value_key_id, custom_headers, custom_headers_key_id, tool_allow_list, tool_deny_list, availability, enabled, created_by, updated_by, created_at, updated_at
`

type InsertMCPServerConfigParams struct {
	DisplayName             string         `db:"display_name" json:"display_name"`
	Slug                    string         `db:"slug" json:"slug"`
	Description             string         `db:"description" json:"description"`
	IconURL                 string         `db:"icon_url" json:"icon_url"`
	Transport               string         `db:"transport" json:"transport"`
	Url                     string         `db:"url" json:"url"`
	AuthType                string         `db:"auth_type" json:"auth_type"`
	OAuth2ClientID          string         `db:"oauth2_client_id" json:"oauth2_client_id"`
	OAuth2ClientSecret      string         `db:"oauth2_client_secret" json:"oauth2_client_secret"`
	OAuth2ClientSecretKeyID sql.NullString `db:"oauth2_client_secret_key_id" json:"oauth2_client_secret_key_id"`
	OAuth2AuthURL           string         `db:"oauth2_auth_url" json:"oauth2_auth_url"`
	OAuth2TokenURL          string         `db:"oauth2_token_url" json:"oauth2_token_url"`
	OAuth2Scopes            string         `db:"oauth2_scopes" json:"oauth2_scopes"`
	APIKeyHeader            string         `db:"api_key_header" json:"api_key_header"`
	APIKeyValue             string         `db:"api_key_value" json:"api_key_value"`
	APIKeyValueKeyID        sql.NullString `db:"api_key_value_key_id" json:"api_key_value_key_id"`
	CustomHeaders           string         `db:"custom_headers" json:"custom_headers"`
	CustomHeadersKeyID      sql.NullString `db:"custom_headers_key_id" json:"custom_headers_key_id"`
	ToolAllowList           []string       `db:"tool_allow_list" json:"tool_allow_list"`
	ToolDenyList            []string       `db:"tool_deny_list" json:"tool_deny_list"`
	Availability            string         `db:"availability" json:"availability"`
	Enabled                 bool           `db:"enabled" json:"enabled"`
	CreatedBy               uuid.UUID      `db:"created_by" json:"created_by"`
	UpdatedBy               uuid.UUID      `db:"updated_by" json:"updated_by"`
}

func (q *Queries) InsertMCPServerConfig(ctx context.Context, arg InsertMCPServerConfigParams) (MCPServerConfig, error) {
	row := q.db.QueryRowContext(ctx, insertMCPServerConfig,
		arg.DisplayName,
		arg.Slug,
		arg.Description,
		arg.IconURL,
		arg.Transport,
		arg.Url,
		arg.AuthType,
		arg.OAuth2ClientID,
		arg.OAuth2ClientSecret,
		arg.OAuth2ClientSecretKeyID,
		arg.OAuth2AuthURL,
		arg.OAuth2TokenURL,
		arg.OAuth2Scopes,
		arg.APIKeyHeader,
		arg.APIKeyValue,
		arg.APIKeyValueKeyID,
		arg.CustomHeaders,
		arg.CustomHeadersKeyID,
		pq.Array(arg.ToolAllowList),
		pq.Array(arg.ToolDenyList),
		arg.Availability,
		arg.Enabled,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i MCPServerConfig
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Slug,
		&i.Description,
		&i.IconURL,
		&i.Transport,
		&i.Url,
		&i.AuthType,
		&i.OAuth2ClientID,
		&i.OAuth2ClientSecret,
		&i.OAuth2ClientSecretKeyID,
		&i.OAuth2AuthURL,
		&i.OAuth2TokenURL,
		&i.OAuth2Scopes,
		&i.APIKeyHeader,
		&i.APIKeyValue,
		&i.APIKeyValueKeyID,
		&i.CustomHeaders,
		&i.CustomHeadersKeyID,
		pq.Array(&i.ToolAllowList),
		pq.Array(&i.ToolDenyList),
		&i.Availability,
		&i.Enabled,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMCPServerConfig = `-- name: UpdateMCPServerConfig :one
UPDATE
    mcp_server_configs
SET
    display_name = $1::text,
    slug = $2::text,
    description = $3::text,
    icon_url = $4::text,
    transport = $5::text,
    url = $6::text,
    auth_type = $7::text,
    oauth2_client_id = $8::text,
    oauth2_client_secret = $9::text,
    oauth2_client_secret_key_id = $10::text,
    oauth2_auth_url = $11::text,
    oauth2_token_url = $12::text,
    oauth2_scopes = $13::text,
    api_key_header = $14::text,
    api_key_value = $15::text,
    api_key_value_key_id = $16::text,
    custom_headers = $17::text,
    custom_headers_key_id = $18::text,
    tool_allow_list = $19::text[],
    tool_deny_list = $20::text[],
    availability = $21::text,
    enabled = $22::boolean,
    updated_by = $23::uuid,
    updated_at = NOW()
WHERE
    id = $24::uuid
RETURNING
    id, display_name, slug, description, icon_url, transport, url, auth_type, oauth2_client_id, oauth2_client_secret, oauth2_client_secret_key_id, oauth2_auth_url, oauth2_token_url, oauth2_scopes, api_key_header, api_key_value, api_key_value_key_id, custom_headers, custom_headers_key_id, tool_allow_list, tool_deny_list, availability, enabled, created_by, updated_by, created_at, updated_at
`

type UpdateMCPServerConfigParams struct {
	DisplayName             string         `db:"display_name" json:"display_name"`
	Slug                    string         `db:"slug" json:"slug"`
	Description             string         `db:"description" json:"description"`
	IconURL                 string         `db:"icon_url" json:"icon_url"`
	Transport               string         `db:"transport" json:"transport"`
	Url                     string         `db:"url" json:"url"`
	AuthType                string         `db:"auth_type" json:"auth_type"`
	OAuth2ClientID          string         `db:"oauth2_client_id" json:"oauth2_client_id"`
	OAuth2ClientSecret      string         `db:"oauth2_client_secret" json:"oauth2_client_secret"`
	OAuth2ClientSecretKeyID sql.NullString `db:"oauth2_client_secret_key_id" json:"oauth2_client_secret_key_id"`
	OAuth2AuthURL           string         `db:"oauth2_auth_url" json:"oauth2_auth_url"`
	OAuth2TokenURL          string         `db:"oauth2_token_url" json:"oauth2_token_url"`
	OAuth2Scopes            string         `db:"oauth2_scopes" json:"oauth2_scopes"`
	APIKeyHeader            string         `db:"api_key_header" json:"api_key_header"`
	APIKeyValue             string         `db:"api_key_value" json:"api_key_value"`
	APIKeyValueKeyID        sql.NullString `db:"api_key_value_key_id" json:"api_key_value_key_id"`
	CustomHeaders           string         `db:"custom_headers" json:"custom_headers"`
	CustomHeadersKeyID      sql.NullString `db:"custom_headers_key_id" json:"custom_headers_key_id"`
	ToolAllowList           []string       `db:"tool_allow_list" json:"tool_allow_list"`
	ToolDenyList            []string       `db:"tool_deny_list" json:"tool_deny_list"`
	Availability            string         `db:"availability" json:"availability"`
	Enabled                 bool           `db:"enabled" json:"enabled"`
	UpdatedBy               uuid.UUID      `db:"updated_by" json:"updated_by"`
	ID                      uuid.UUID      `db:"id" json:"id"`
}

func (q *Queries) UpdateMCPServerConfig(ctx context.Context, arg UpdateMCPServerConfigParams) (MCPServerConfig, error) {
	row := q.db.QueryRowContext(ctx, updateMCPServerConfig,
		arg.DisplayName,
		arg.Slug,
		arg.Description,
		arg.IconURL,
		arg.Transport,
		arg.Url,
		arg.AuthType,
		arg.OAuth2ClientID,
		arg.OAuth2ClientSecret,
		arg.OAuth2ClientSecretKeyID,
		arg.OAuth2AuthURL,
		arg.OAuth2TokenURL,
		arg.OAuth2Scopes,
		arg.APIKeyHeader,
		arg.APIKeyValue,
		arg.APIKeyValueKeyID,
		arg.CustomHeaders,
		arg.CustomHeadersKeyID,
		pq.Array(arg.ToolAllowList),
		pq.Array(arg.ToolDenyList),
		arg.Availability,
		arg.Enabled,
		arg.UpdatedBy,
		arg.ID,
	)
	var i MCPServerConfig
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Slug,
		&i.Description,
		&i.IconURL,
		&i.Transport,
		&i.Url,
		&i.AuthType,
		&i.OAuth2ClientID,
		&i.OAuth2ClientSecret,
		&i.OAuth2ClientSecretKeyID,
		&i.OAuth2AuthURL,
		&i.OAuth2TokenURL,
		&i.OAuth2Scopes,
		&i.APIKeyHeader,
		&i.APIKeyValue,
		&i.APIKeyValueKeyID,
		&i.CustomHeaders,
		&i.CustomHeadersKeyID,
		pq.Array(&i.ToolAllowList),
		pq.Array(&i.ToolDenyList),
		&i.Availability,
		&i.Enabled,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMCPServerUserToken = `-- name: UpsertMCPServerUserToken :one
INSERT INTO mcp_server_user_tokens (
    mcp_server_config_id,
    user_id,
    access_token,
    access_token_key_id,
    refresh_token,
    refresh_token_key_id,
    token_type,
    expiry
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::text,
    $5::text,
    $6::text,
    $7::text,
    $8::timestamptz
)
ON CONFLICT (mcp_server_config_id, user_id) DO UPDATE SET
    access_token = $3::text,
    access_token_key_id = $4::text,
    refresh_token = $5::text,
    refresh_token_key_id = $6::text,
    token_type = $7::text,
    expiry = $8::timestamptz,
    updated_at = NOW()
RETURNING
    id, mcp_server_config_id, user_id, access_token, access_token_key_id, refresh_token, refresh_token_key_id, token_type, expiry, created_at, updated_at
`

type UpsertMCPServerUserTokenParams struct {
	MCPServerConfigID uuid.UUID      `db:"mcp_server_config_id" json:"mcp_server_config_id"`
	UserID            uuid.UUID      `db:"user_id" json:"user_id"`
	AccessToken       string         `db:"access_token" json:"access_token"`
	AccessTokenKeyID  sql.NullString `db:"access_token_key_id" json:"access_token_key_id"`
	RefreshToken      string         `db:"refresh_token" json:"refresh_token"`
	RefreshTokenKeyID sql.NullString `db:"refresh_token_key_id" json:"refresh_token_key_id"`
	TokenType         string         `db:"token_type" json:"token_type"`
	Expiry            sql.NullTime   `db:"expiry" json:"expiry"`
}

func (q *Queries) UpsertMCPServerUserToken(ctx context.Context, arg UpsertMCPServerUserTokenParams) (MCPServerUserToken, error) {
	row := q.db.QueryRowContext(ctx, upsertMCPServerUserToken,
		arg.MCPServerConfigID,
		arg.UserID,
		arg.AccessToken,
		arg.AccessTokenKeyID,
		arg.RefreshToken,
		arg.RefreshTokenKeyID,
		arg.TokenType,
		arg.Expiry,
	)
	var i MCPServerUserToken
	err := row.Scan(
		&i.ID,
		&i.MCPServerConfigID,
		&i.UserID,
		&i.AccessToken,
		&i.AccessTokenKeyID,
		&i.RefreshToken,
		&i.RefreshTokenKeyID,
		&i.TokenType,
		&i.Expiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
