// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteTask = `-- name: DeleteTask :one
WITH deleted_task AS (
	UPDATE tasks
	SET
		deleted_at = $1::timestamptz
	WHERE
		id = $2::uuid
		AND deleted_at IS NULL
	RETURNING id
), deleted_snapshot AS (
	DELETE FROM task_snapshots
	WHERE task_id = $2::uuid
)
SELECT id FROM deleted_task
`

type DeleteTaskParams struct {
	DeletedAt time.Time `db:"deleted_at" json:"deleted_at"`
	ID        uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteTask, arg.DeletedAt, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, organization_id, owner_id, name, workspace_id, template_version_id, template_parameters, prompt, created_at, deleted_at, display_name, workspace_group_acl, workspace_user_acl, status, status_debug, workspace_build_number, workspace_agent_id, workspace_app_id, workspace_agent_lifecycle_state, workspace_app_health, owner_username, owner_name, owner_avatar_url FROM tasks_with_status WHERE id = $1::uuid
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.Name,
		&i.WorkspaceID,
		&i.TemplateVersionID,
		&i.TemplateParameters,
		&i.Prompt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DisplayName,
		&i.WorkspaceGroupACL,
		&i.WorkspaceUserACL,
		&i.Status,
		&i.StatusDebug,
		&i.WorkspaceBuildNumber,
		&i.WorkspaceAgentID,
		&i.WorkspaceAppID,
		&i.WorkspaceAgentLifecycleState,
		&i.WorkspaceAppHealth,
		&i.OwnerUsername,
		&i.OwnerName,
		&i.OwnerAvatarUrl,
	)
	return i, err
}

const getTaskByOwnerIDAndName = `-- name: GetTaskByOwnerIDAndName :one
SELECT id, organization_id, owner_id, name, workspace_id, template_version_id, template_parameters, prompt, created_at, deleted_at, display_name, workspace_group_acl, workspace_user_acl, status, status_debug, workspace_build_number, workspace_agent_id, workspace_app_id, workspace_agent_lifecycle_state, workspace_app_health, owner_username, owner_name, owner_avatar_url FROM tasks_with_status
WHERE
	owner_id = $1::uuid
	AND deleted_at IS NULL
	AND LOWER(name) = LOWER($2::text)
`

type GetTaskByOwnerIDAndNameParams struct {
	OwnerID uuid.UUID `db:"owner_id" json:"owner_id"`
	Name    string    `db:"name" json:"name"`
}

func (q *Queries) GetTaskByOwnerIDAndName(ctx context.Context, arg GetTaskByOwnerIDAndNameParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByOwnerIDAndName, arg.OwnerID, arg.Name)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.Name,
		&i.WorkspaceID,
		&i.TemplateVersionID,
		&i.TemplateParameters,
		&i.Prompt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DisplayName,
		&i.WorkspaceGroupACL,
		&i.WorkspaceUserACL,
		&i.Status,
		&i.StatusDebug,
		&i.WorkspaceBuildNumber,
		&i.WorkspaceAgentID,
		&i.WorkspaceAppID,
		&i.WorkspaceAgentLifecycleState,
		&i.WorkspaceAppHealth,
		&i.OwnerUsername,
		&i.OwnerName,
		&i.OwnerAvatarUrl,
	)
	return i, err
}

const getTaskByWorkspaceID = `-- name: GetTaskByWorkspaceID :one
SELECT id, organization_id, owner_id, name, workspace_id, template_version_id, template_parameters, prompt, created_at, deleted_at, display_name, workspace_group_acl, workspace_user_acl, status, status_debug, workspace_build_number, workspace_agent_id, workspace_app_id, workspace_agent_lifecycle_state, workspace_app_health, owner_username, owner_name, owner_avatar_url FROM tasks_with_status WHERE workspace_id = $1::uuid
`

func (q *Queries) GetTaskByWorkspaceID(ctx context.Context, workspaceID uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByWorkspaceID, workspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.Name,
		&i.WorkspaceID,
		&i.TemplateVersionID,
		&i.TemplateParameters,
		&i.Prompt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DisplayName,
		&i.WorkspaceGroupACL,
		&i.WorkspaceUserACL,
		&i.Status,
		&i.StatusDebug,
		&i.WorkspaceBuildNumber,
		&i.WorkspaceAgentID,
		&i.WorkspaceAppID,
		&i.WorkspaceAgentLifecycleState,
		&i.WorkspaceAppHealth,
		&i.OwnerUsername,
		&i.OwnerName,
		&i.OwnerAvatarUrl,
	)
	return i, err
}

const getTaskSnapshot = `-- name: GetTaskSnapshot :one
SELECT
	task_id, log_snapshot, log_snapshot_created_at
FROM
	task_snapshots
WHERE
	task_id = $1
`

func (q *Queries) GetTaskSnapshot(ctx context.Context, taskID uuid.UUID) (TaskSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getTaskSnapshot, taskID)
	var i TaskSnapshot
	err := row.Scan(&i.TaskID, &i.LogSnapshot, &i.LogSnapshotCreatedAt)
	return i, err
}

const getTelemetryTaskEvents = `-- name: GetTelemetryTaskEvents :many
WITH task_app_ids AS (
	SELECT task_id, workspace_app_id
	FROM task_workspace_apps
),
task_status_timeline AS (
	-- All app statuses across every historical app for each task,
	-- plus synthetic "boundary" rows at each stop/start build transition.
	-- This allows us to correctly take gaps due to pause/resume into account.
	SELECT tai.task_id, was.created_at, was.state::text AS state
	FROM workspace_app_statuses was
	JOIN task_app_ids tai ON tai.workspace_app_id = was.app_id
	UNION ALL
	SELECT t.id AS task_id, wb.created_at, '_boundary' AS state
	FROM tasks t
	JOIN workspace_builds wb ON wb.workspace_id = t.workspace_id
	WHERE t.deleted_at IS NULL
		AND t.workspace_id IS NOT NULL
		AND wb.build_number > 1
),
task_event_data AS (
	SELECT
		t.id AS task_id,
		t.workspace_id,
		twa.workspace_app_id,
		-- Latest stop build.
		stop_build.created_at AS stop_build_created_at,
		stop_build.reason AS stop_build_reason,
		-- Latest start build (task_resume only).
		start_build.created_at AS start_build_created_at,
		start_build.reason AS start_build_reason,
		start_build.build_number AS start_build_number,
		-- Last "working" app status (for idle duration).
		lws.created_at AS last_working_status_at,
		-- First app status after resume (for resume-to-status duration).
		-- Only populated for workspaces in an active phase (started more
		-- recently than stopped).
		fsar.created_at AS first_status_after_resume_at,
		-- Cumulative time spent in "working" state.
		active_dur.total_working_ms AS active_duration_ms
	FROM tasks t
	LEFT JOIN LATERAL (
		SELECT task_app.workspace_app_id
		FROM task_workspace_apps task_app
		WHERE task_app.task_id = t.id
		ORDER BY task_app.workspace_build_number DESC
		LIMIT 1
	) twa ON TRUE
	LEFT JOIN LATERAL (
		SELECT wb.created_at, wb.reason, wb.build_number
		FROM workspace_builds wb
		WHERE wb.workspace_id = t.workspace_id
			AND wb.transition = 'stop'
		ORDER BY wb.build_number DESC
		LIMIT 1
	) stop_build ON TRUE
	LEFT JOIN LATERAL (
		SELECT wb.created_at, wb.reason, wb.build_number
		FROM workspace_builds wb
		WHERE wb.workspace_id = t.workspace_id
			AND wb.transition = 'start'
		ORDER BY wb.build_number DESC
		LIMIT 1
	) start_build ON TRUE
	LEFT JOIN LATERAL (
		SELECT tst.created_at
		FROM task_status_timeline tst
		WHERE tst.task_id = t.id
			AND tst.state = 'working'
		-- Only consider status before the latest pause so that
		-- post-resume statuses don't mask pre-pause idle time.
		AND (stop_build.created_at IS NULL
			OR tst.created_at <= stop_build.created_at)
		ORDER BY tst.created_at DESC
		LIMIT 1
	) lws ON TRUE
	LEFT JOIN LATERAL (
		SELECT was.created_at
		FROM workspace_app_statuses was
		WHERE was.app_id = twa.workspace_app_id
			AND was.created_at > start_build.created_at
		ORDER BY was.created_at ASC
		LIMIT 1
	) fsar ON twa.workspace_app_id IS NOT NULL
		AND start_build.created_at IS NOT NULL
		AND (stop_build.created_at IS NULL
			OR start_build.created_at > stop_build.created_at)
	-- Active duration: cumulative time spent in "working" state across all
	-- historical app IDs for this task. Uses LEAD() to convert point-in-time
	-- statuses into intervals, then sums intervals where state='working'. For
	-- the last status, falls back to stop_build time (if paused) or @now (if
	-- still running).
	LEFT JOIN LATERAL (
		SELECT COALESCE(
			SUM(EXTRACT(EPOCH FROM (interval_end - interval_start)) * 1000)::bigint,
			0
		)::bigint AS total_working_ms
		FROM (
			SELECT
				tst.created_at AS interval_start,
				COALESCE(
					LEAD(tst.created_at) OVER (ORDER BY tst.created_at ASC, CASE WHEN tst.state = '_boundary' THEN 1 ELSE 0 END ASC),
					CASE WHEN stop_build.created_at IS NOT NULL
						AND (start_build.created_at IS NULL
							OR stop_build.created_at > start_build.created_at)
					THEN stop_build.created_at
					ELSE $1::timestamptz
					END
				) AS interval_end,
				tst.state
			FROM task_status_timeline tst
			WHERE tst.task_id = t.id
		) intervals
		WHERE intervals.state = 'working'
	) active_dur ON TRUE
	WHERE t.deleted_at IS NULL
		AND t.workspace_id IS NOT NULL
		AND EXISTS (
			SELECT 1 FROM workspace_builds wb
			WHERE wb.workspace_id = t.workspace_id
			  AND wb.created_at > $2
		)
)
SELECT task_id, workspace_id, workspace_app_id, stop_build_created_at, stop_build_reason, start_build_created_at, start_build_reason, start_build_number, last_working_status_at, first_status_after_resume_at, active_duration_ms FROM task_event_data
ORDER BY task_id
`

type GetTelemetryTaskEventsParams struct {
	Now          time.Time `db:"now" json:"now"`
	CreatedAfter time.Time `db:"created_after" json:"created_after"`
}

type GetTelemetryTaskEventsRow struct {
	TaskID                   uuid.UUID       `db:"task_id" json:"task_id"`
	WorkspaceID              uuid.NullUUID   `db:"workspace_id" json:"workspace_id"`
	WorkspaceAppID           uuid.NullUUID   `db:"workspace_app_id" json:"workspace_app_id"`
	StopBuildCreatedAt       sql.NullTime    `db:"stop_build_created_at" json:"stop_build_created_at"`
	StopBuildReason          NullBuildReason `db:"stop_build_reason" json:"stop_build_reason"`
	StartBuildCreatedAt      sql.NullTime    `db:"start_build_created_at" json:"start_build_created_at"`
	StartBuildReason         NullBuildReason `db:"start_build_reason" json:"start_build_reason"`
	StartBuildNumber         sql.NullInt32   `db:"start_build_number" json:"start_build_number"`
	LastWorkingStatusAt      sql.NullTime    `db:"last_working_status_at" json:"last_working_status_at"`
	FirstStatusAfterResumeAt sql.NullTime    `db:"first_status_after_resume_at" json:"first_status_after_resume_at"`
	ActiveDurationMs         int64           `db:"active_duration_ms" json:"active_duration_ms"`
}

// Returns all data needed to build task lifecycle events for telemetry
// in a single round-trip. For each task whose workspace is in the
// given set, fetches:
//   - the latest workspace app binding (task_workspace_apps)
//   - the most recent stop and start builds (workspace_builds)
//   - the last "working" app status (workspace_app_statuses)
//   - the first app status after resume, for active workspaces
//
// Assumptions:
//   - 1:1 relationship between tasks and workspaces. All builds on the
//     workspace are considered task-related.
//   - Idle duration approximation: If the agent reports "working", does
//     work, then reports "done", we miss that working time.
//   - lws and active_dur join across all historical app IDs for the task,
//     because each resume cycle provisions a new app ID. This ensures
//     pre-pause statuses contribute to idle duration and active duration.
func (q *Queries) GetTelemetryTaskEvents(ctx context.Context, arg GetTelemetryTaskEventsParams) ([]GetTelemetryTaskEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTelemetryTaskEvents, arg.Now, arg.CreatedAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTelemetryTaskEventsRow
	for rows.Next() {
		var i GetTelemetryTaskEventsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.WorkspaceID,
			&i.WorkspaceAppID,
			&i.StopBuildCreatedAt,
			&i.StopBuildReason,
			&i.StartBuildCreatedAt,
			&i.StartBuildReason,
			&i.StartBuildNumber,
			&i.LastWorkingStatusAt,
			&i.FirstStatusAfterResumeAt,
			&i.ActiveDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks
	(id, organization_id, owner_id, name, display_name, workspace_id, template_version_id, template_parameters, prompt, created_at)
VALUES
	($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, organization_id, owner_id, name, workspace_id, template_version_id, template_parameters, prompt, created_at, deleted_at, display_name
`

type InsertTaskParams struct {
	ID                 uuid.UUID       `db:"id" json:"id"`
	OrganizationID     uuid.UUID       `db:"organization_id" json:"organization_id"`
	OwnerID            uuid.UUID       `db:"owner_id" json:"owner_id"`
	Name               string          `db:"name" json:"name"`
	DisplayName        string          `db:"display_name" json:"display_name"`
	WorkspaceID        uuid.NullUUID   `db:"workspace_id" json:"workspace_id"`
	TemplateVersionID  uuid.UUID       `db:"template_version_id" json:"template_version_id"`
	TemplateParameters json.RawMessage `db:"template_parameters" json:"template_parameters"`
	Prompt             string          `db:"prompt" json:"prompt"`
	CreatedAt          time.Time       `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (TaskTable, error) {
	row := q.db.QueryRowContext(ctx, insertTask,
		arg.ID,
		arg.OrganizationID,
		arg.OwnerID,
		arg.Name,
		arg.DisplayName,
		arg.WorkspaceID,
		arg.TemplateVersionID,
		arg.TemplateParameters,
		arg.Prompt,
		arg.CreatedAt,
	)
	var i TaskTable
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.Name,
		&i.WorkspaceID,
		&i.TemplateVersionID,
		&i.TemplateParameters,
		&i.Prompt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DisplayName,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, organization_id, owner_id, name, workspace_id, template_version_id, template_parameters, prompt, created_at, deleted_at, display_name, workspace_group_acl, workspace_user_acl, status, status_debug, workspace_build_number, workspace_agent_id, workspace_app_id, workspace_agent_lifecycle_state, workspace_app_health, owner_username, owner_name, owner_avatar_url FROM tasks_with_status tws
WHERE tws.deleted_at IS NULL
AND CASE WHEN $1::UUID != '00000000-0000-0000-0000-000000000000' THEN tws.owner_id = $1::UUID ELSE TRUE END
AND CASE WHEN $2::UUID != '00000000-0000-0000-0000-000000000000' THEN tws.organization_id = $2::UUID ELSE TRUE END
AND CASE WHEN $3::text != '' THEN tws.status = $3::task_status ELSE TRUE END
ORDER BY tws.created_at DESC
`

type ListTasksParams struct {
	OwnerID        uuid.UUID `db:"owner_id" json:"owner_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Status         string    `db:"status" json:"status"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, arg.OwnerID, arg.OrganizationID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OwnerID,
			&i.Name,
			&i.WorkspaceID,
			&i.TemplateVersionID,
			&i.TemplateParameters,
			&i.Prompt,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.DisplayName,
			&i.WorkspaceGroupACL,
			&i.WorkspaceUserACL,
			&i.Status,
			&i.StatusDebug,
			&i.WorkspaceBuildNumber,
			&i.WorkspaceAgentID,
			&i.WorkspaceAppID,
			&i.WorkspaceAgentLifecycleState,
			&i.WorkspaceAppHealth,
			&i.OwnerUsername,
			&i.OwnerName,
			&i.OwnerAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskPrompt = `-- name: UpdateTaskPrompt :one
UPDATE
	tasks
SET
	prompt = $1::text
WHERE
	id = $2::uuid
	AND deleted_at IS NULL
RETURNING id, organization_id, owner_id, name, workspace_id, template_version_id, template_parameters, prompt, created_at, deleted_at, display_name
`

type UpdateTaskPromptParams struct {
	Prompt string    `db:"prompt" json:"prompt"`
	ID     uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateTaskPrompt(ctx context.Context, arg UpdateTaskPromptParams) (TaskTable, error) {
	row := q.db.QueryRowContext(ctx, updateTaskPrompt, arg.Prompt, arg.ID)
	var i TaskTable
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.Name,
		&i.WorkspaceID,
		&i.TemplateVersionID,
		&i.TemplateParameters,
		&i.Prompt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DisplayName,
	)
	return i, err
}

const updateTaskWorkspaceID = `-- name: UpdateTaskWorkspaceID :one
UPDATE
	tasks
SET
	workspace_id = $2
FROM
	workspaces w
JOIN
	template_versions tv
ON
	tv.template_id = w.template_id
WHERE
	tasks.id = $1
	AND tasks.workspace_id IS NULL
	AND w.id = $2
	AND tv.id = tasks.template_version_id
RETURNING
	tasks.id, tasks.organization_id, tasks.owner_id, tasks.name, tasks.workspace_id, tasks.template_version_id, tasks.template_parameters, tasks.prompt, tasks.created_at, tasks.deleted_at, tasks.display_name
`

type UpdateTaskWorkspaceIDParams struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	WorkspaceID uuid.NullUUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) UpdateTaskWorkspaceID(ctx context.Context, arg UpdateTaskWorkspaceIDParams) (TaskTable, error) {
	row := q.db.QueryRowContext(ctx, updateTaskWorkspaceID, arg.ID, arg.WorkspaceID)
	var i TaskTable
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.Name,
		&i.WorkspaceID,
		&i.TemplateVersionID,
		&i.TemplateParameters,
		&i.Prompt,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.DisplayName,
	)
	return i, err
}

const upsertTaskSnapshot = `-- name: UpsertTaskSnapshot :exec
INSERT INTO
	task_snapshots (task_id, log_snapshot, log_snapshot_created_at)
VALUES
	($1, $2, $3)
ON CONFLICT
	(task_id)
DO UPDATE SET
	log_snapshot = EXCLUDED.log_snapshot,
	log_snapshot_created_at = EXCLUDED.log_snapshot_created_at
`

type UpsertTaskSnapshotParams struct {
	TaskID               uuid.UUID       `db:"task_id" json:"task_id"`
	LogSnapshot          json.RawMessage `db:"log_snapshot" json:"log_snapshot"`
	LogSnapshotCreatedAt time.Time       `db:"log_snapshot_created_at" json:"log_snapshot_created_at"`
}

func (q *Queries) UpsertTaskSnapshot(ctx context.Context, arg UpsertTaskSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertTaskSnapshot, arg.TaskID, arg.LogSnapshot, arg.LogSnapshotCreatedAt)
	return err
}

const upsertTaskWorkspaceApp = `-- name: UpsertTaskWorkspaceApp :one
INSERT INTO task_workspace_apps
	(task_id, workspace_build_number, workspace_agent_id, workspace_app_id)
VALUES
	($1, $2, $3, $4)
ON CONFLICT (task_id, workspace_build_number)
DO UPDATE SET
	workspace_agent_id = EXCLUDED.workspace_agent_id,
	workspace_app_id = EXCLUDED.workspace_app_id
RETURNING task_id, workspace_agent_id, workspace_app_id, workspace_build_number
`

type UpsertTaskWorkspaceAppParams struct {
	TaskID               uuid.UUID     `db:"task_id" json:"task_id"`
	WorkspaceBuildNumber int32         `db:"workspace_build_number" json:"workspace_build_number"`
	WorkspaceAgentID     uuid.NullUUID `db:"workspace_agent_id" json:"workspace_agent_id"`
	WorkspaceAppID       uuid.NullUUID `db:"workspace_app_id" json:"workspace_app_id"`
}

func (q *Queries) UpsertTaskWorkspaceApp(ctx context.Context, arg UpsertTaskWorkspaceAppParams) (TaskWorkspaceApp, error) {
	row := q.db.QueryRowContext(ctx, upsertTaskWorkspaceApp,
		arg.TaskID,
		arg.WorkspaceBuildNumber,
		arg.WorkspaceAgentID,
		arg.WorkspaceAppID,
	)
	var i TaskWorkspaceApp
	err := row.Scan(
		&i.TaskID,
		&i.WorkspaceAgentID,
		&i.WorkspaceAppID,
		&i.WorkspaceBuildNumber,
	)
	return i, err
}
