import { useTranslation } from "react-i18next";

// Hook to get translated language strings for WorkspacePage (detail view)
export const useWorkspaceDetailLanguage = () => {
	const { t } = useTranslation("workspaceDetail");

	return {
		title: t("title"),
		backToWorkspaces: t("backToWorkspaces"),
		owner: t("owner"),
		organization: t("organization"),
		version: t("version"),
		copyWorkspaceName: t("copyWorkspaceName"),
		dailyUsage: t("dailyUsage"),
		creditsOf: t("creditsOf"),
		seeAffectedWorkspaces: t("seeAffectedWorkspaces"),
		seeAffectedWorkspacesFor: (org: string) =>
			t("seeAffectedWorkspacesFor", { org }),
		deletionOn: (date: string) => t("deletionOn", { date }),
		deletionSoon: t("deletionSoon"),
		scheduleSettings: t("scheduleSettings"),
		restartWorkspace: t("restartWorkspace"),
		restartConfirm: t("restartConfirm"),
		restartDescription: t("restartDescription"),
		failedToBuild: (name: string) => t("failedToBuild", { name }),
		pleaseTryRefreshing: t("pleaseTryRefreshing"),
		unableToProcessData: (name: string) => t("unableToProcessData", { name }),
		unableToGetChanges: (name: string) => t("unableToGetChanges", { name }),
		connectionClosed: t("connectionClosed"),
		errorActivating: (name: string) => t("errorActivating", { name }),
		status: {
			title: t("status.title"),
			starting: t("status.starting"),
			running: t("status.running"),
			stopping: t("status.stopping"),
			stopped: t("status.stopped"),
			error: t("status.error"),
			pending: t("status.pending"),
			canceling: t("status.canceling"),
			canceled: t("status.canceled"),
			deleting: t("status.deleting"),
			deleted: t("status.deleted"),
			updating: t("status.updating"),
			deleting_date: (date: string) => t("status.deleting_date", { date }),
		},
		resources: {
			title: t("resources.title"),
			cpu: t("resources.cpu"),
			memory: t("resources.memory"),
			disk: t("resources.disk"),
			network: t("resources.network"),
			uptime: t("resources.uptime"),
			lastUsed: t("resources.lastUsed"),
		},
		actions: {
			start: t("actions.start"),
			stop: t("actions.stop"),
			restart: t("actions.restart"),
			update: t("actions.update"),
			delete: t("actions.delete"),
			openSSH: t("actions.openSSH"),
			openVSCode: t("actions.openVSCode"),
			openBrowser: t("actions.openBrowser"),
			viewLogs: t("actions.viewLogs"),
			viewHistory: t("actions.viewHistory"),
			viewTemplates: t("actions.viewTemplates"),
			settings: t("actions.settings"),
			autoUpdateRequired: t("actions.autoUpdateRequired"),
			autoUpdateRequiredRestart: t("actions.autoUpdateRequiredRestart"),
			autoUpdateEnabled: t("actions.autoUpdateEnabled"),
		},
		messages: {
			updatedSuccessfully: (name: string) =>
				t("messages.updatedSuccessfully", { name }),
			updateFailed: (name: string) => t("messages.updateFailed", { name }),
		},
		stopIn: (duration: string) => t("stopIn", { duration }),
		subtractHour: t("subtractHour"),
		addHour: t("addHour"),
		updateAndRestart: t("updateAndRestart"),
		restart: t("restart"),
		restartWithParams: t("restartWithParams"),
		favorite: t("favorite"),
		share: t("share"),
		resourcesTab: t("resourcesTab"),
		historyTab: t("historyTab"),
		resourcesFailed: t("resourcesFailed"),
		showMoreBuilds: t("showMoreBuilds"),
		ready: t("ready"),
		connectViaSSH: t("connectViaSSH"),
		appsWarning: {
			title: t("appsWarning.title"),
			message: t("appsWarning.message"),
			message2: t("appsWarning.message2"),
			message3: t("appsWarning.message3"),
			learnMore: t("appsWarning.learnMore"),
		},
		vscodeDesktop: t("vscodeDesktop"),
		terminal: t("terminal"),
		logs: t("logs"),
		downloadLogs: t("downloadLogs"),
		buildTimeline: t("buildTimeline"),
		health: {
			agentsNotConnected: t("health.agentsNotConnected"),
			cannotBeUsed: t("health.cannotBeUsed"),
			agentsDisconnected: t("health.agentsDisconnected"),
			disconnectedMessage: t("health.disconnectedMessage"),
			startingNotConnected: t("health.startingNotConnected"),
			timeoutMessage: t("health.timeoutMessage"),
			runningBut: t("health.runningBut"),
			multipleAgentsNotConnected: (count: number) =>
				t("health.multipleAgentsNotConnected", { count }),
			singleAgentNotConnected: t("health.singleAgentNotConnected"),
			viewDocsToTroubleshoot: t("health.viewDocsToTroubleshoot"),
		},
	};
};
